Cotton::Builtin::NothingInstance Class Reference
#include <nothing.h>
Public Member Functions
NothingInstance (Runtime *rt)
~NothingInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
NothingInstance()
Cotton::Builtin::NothingInstance::NothingInstance (Runtime * rt)
References ProfilerCAPTURE.
Referenced by copy(), and getSize().
 NothingInstance()
Cotton::Builtin::NothingInstance::~NothingInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::NothingInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), NothingInstance(), ProfilerCAPTURE, Cotton::Runtime::signalError(), and userRepr().
getSize()
size_t Cotton::Builtin::NothingInstance::getSize () [virtual]
Implements Cotton::Instance.
References NothingInstance(), and ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::NothingInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE.
Referenced by copy().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/nothing.h
cotton_lib/src/cotton_lib/builtin/types/nothing.cpp