Cotton::Builtin::FunctionType Class Reference
#include <function.h>
Public Member Functions
size_t getInstanceSize ()
FunctionType (Runtime *rt)
~FunctionType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
FunctionType()
Cotton::Builtin::FunctionType::FunctionType (Runtime * rt)
References Cotton::Type::call_op, Cotton::Type::eq_op, Cotton::Builtin::FunctionCallAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::FunctionNeqAdapter(), Cotton::Type::neq_op, and ProfilerCAPTURE.
 FunctionType()
Cotton::Builtin::FunctionType::~FunctionType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::FunctionType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Instance::copy(), Cotton::Runtime::function_type, Cotton::Object::instance, newObject, ProfilerCAPTURE, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::FunctionType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::FunctionType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::FunctionType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/function.h
cotton_lib/src/cotton_lib/builtin/types/function.cpp