Cotton::NameIds Class Reference
#include <nameid.h>
Public Member Functions
NameId get (Token *token)
NameId get (std::string *str)
NameId get (std::string str)
std::string fromId (int64_t id)
std::string userRepr (int64_t id)
Public Attributes
__gnu_pbds::cc_hash_table< std::string, int64_t > map
__gnu_pbds::cc_hash_table< int64_t, std::string > reverse_map
Member Function Documentation
fromId()
std::string Cotton::NameIds::fromId (int64_t id)
References ProfilerCAPTURE, and reverse_map.
Referenced by Cotton::Runtime::getGlobal(), and userRepr().
get() [1/3]
NameId Cotton::NameIds::get (std::string * str)
References Cotton::NameId::id, map, ProfilerCAPTURE, reverse_map, Cotton::NameId::str, and Cotton::NameId::token.
get() [2/3]
NameId Cotton::NameIds::get (std::string str)
References Cotton::NameId::id, map, ProfilerCAPTURE, reverse_map, Cotton::NameId::token, and Cotton::NameId::val_str.
get() [3/3]
NameId Cotton::NameIds::get (Token * token)
References Cotton::Token::data, Cotton::NameId::id, map, ProfilerCAPTURE, reverse_map, Cotton::NameId::str, and Cotton::NameId::token.
Referenced by Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_smartrun(), Cotton::Runtime::execute(), Cotton::Builtin::installArrayMethods(), Cotton::Builtin::installBuiltinFunctions(), Cotton::Builtin::installStringMethods(), library_load_point(), main(), Cotton::MagicMethods::mm__bool__(), Cotton::MagicMethods::mm__char__(), Cotton::MagicMethods::mm__copy__(), Cotton::MagicMethods::mm__int__(), Cotton::MagicMethods::mm__make__(), Cotton::MagicMethods::mm__read__(), Cotton::MagicMethods::mm__real__(), Cotton::MagicMethods::mm__repr__(), Cotton::MagicMethods::mm__string__(), and Cotton::Runtime::Runtime().
userRepr()
std::string Cotton::NameIds::userRepr (int64_t id)
References fromId(), and ProfilerCAPTURE.
Referenced by Cotton::Type::getMethod(), Cotton::Scope::getVariable(), Cotton::Instance::selectField(), Cotton::Builtin::RecordInstance::selectField(), Cotton::Builtin::RecordInstance::userRepr(), and Cotton::Builtin::RecordType::userRepr().
Member Data Documentation
map
__gnu_pbds::cc_hash_table<std::string, int64_t> Cotton::NameIds::map
Referenced by get().
reverse_map
__gnu_pbds::cc_hash_table<int64_t, std::string> Cotton::NameIds::reverse_map
Referenced by fromId(), and get().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/back/nameid.h
cotton_lib/src/cotton_lib/back/nameid.cpp