Cotton::ParExprNode Class Reference
#include <parser.h>
Public Member Functions
ParExprNode ()=delete
~ParExprNode ()
ParExprNode (ExprNode *expr, TextArea text_area)
void print (int indent=0, int step=2)
Public Attributes
TextArea text_area
ExprNode * expr
Constructor & Destructor Documentation
ParExprNode() [1/2]
Cotton::ParExprNode::ParExprNode () [delete]
 ParExprNode()
Cotton::ParExprNode::~ParExprNode ()
References expr.
ParExprNode() [2/2]
Cotton::ParExprNode::ParExprNode (ExprNode * expr, TextArea text_area)
References expr, and text_area.
Member Function Documentation
print()
void Cotton::ParExprNode::print (int indent = 0, int step = 2)
References expr, Cotton::ExprNode::print(), and Cotton::printPrefix().
Referenced by Cotton::ExprNode::print().
Member Data Documentation
expr
ExprNode* Cotton::ParExprNode::expr
Referenced by Cotton::Runtime::execute(), ParExprNode(), print(), and ~ParExprNode().
text_area
TextArea Cotton::ParExprNode::text_area
Referenced by ParExprNode().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/front/parser.h
cotton_lib/src/cotton_lib/front/parser.cpp