Cotton::Builtin::RecordType Class Reference
#include <record.h>
Public Member Functions
size_t getInstanceSize ()
RecordType (Runtime *rt)
~RecordType ()=default
Object * create (Runtime *rt)
std::string userRepr (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
Public Attributes
int64_t nameid
std::vector< int64_t > instance_fields
Constructor & Destructor Documentation
RecordType()
Cotton::Builtin::RecordType::RecordType (Runtime * rt)
References ProfilerCAPTURE.
 RecordType()
Cotton::Builtin::RecordType::~RecordType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::RecordType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Instance::copy(), Cotton::Object::instance, newObject, ProfilerCAPTURE, and Cotton::Runtime::verifyIsValidObject().
create()
Object * Cotton::Builtin::RecordType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References instance_fields, Cotton::Builtin::makeNothingInstanceObject(), newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::RecordType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::RecordType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References nameid, Cotton::Runtime::nds, ProfilerCAPTURE, and Cotton::NameIds::userRepr().
Member Data Documentation
instance_fields
std::vector<int64_t> Cotton::Builtin::RecordType::instance_fields
Referenced by create().
nameid
int64_t Cotton::Builtin::RecordType::nameid
Referenced by userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/record.h
cotton_lib/src/cotton_lib/builtin/types/record.cpp