Cotton::Parser Class Reference
#include <parser.h>
Classes
class OperatorInfo
class ParserState
class ParsingResult
Public Member Functions
Parser ()=delete
~Parser ()=default
Parser (ErrorManager *error_manager)
OperatorInfo getOperatorInfo (Token *token, bool is_pre_op, int special=0)
void goThrough (OperatorInfo op_info)
void saveState ()
void restoreState ()
void highlight (Token *token)
void highlightNext ()
void signalError (const std::string &message)
bool canPassThrough (OperatorInfo op_info)
bool hasNext ()
Token::TokenId checkNext ()
bool consume (Token::TokenId id)
Token::TokenId consume ()
bool hasPrev ()
void rollback ()
ParsingResult parseExpr ()
ParsingResult parseStmt ()
StmtNode * parse (const std::vector< Token > &tokens)
Public Attributes
ErrorManager * error_manager
std::vector< Token > tokens
std::vector< Token >::iterator next_token
ParserState state
std::vector< ParserState > saved_states
std::vector< std::pair< ParserState, std::string > > errors_stack
Constructor & Destructor Documentation
Parser() [1/2]
Cotton::Parser::Parser () [delete]
 Parser()
Cotton::Parser::~Parser () [default]
Parser() [2/2]
Cotton::Parser::Parser (ErrorManager * error_manager)
References error_manager.
Member Function Documentation
canPassThrough()
bool Cotton::Parser::canPassThrough (OperatorInfo op_info)
References Cotton::Parser::OperatorInfo::associativity, Cotton::Parser::ParserState::cur_priority, Cotton::Parser::OperatorInfo::priority, RIGHT_TO_LEFT, and state.
Referenced by parseExpr().
checkNext()
Token::TokenId Cotton::Parser::checkNext ()
References next_token.
Referenced by parseExpr().
consume() [1/2]
Token::TokenId Cotton::Parser::consume ()
References highlight(), next_token, and tokens.
Referenced by parseExpr(), and parseStmt().
consume() [2/2]
bool Cotton::Parser::consume (Token::TokenId id)
References highlight(), and next_token.
Referenced by Cotton::skipSemicolons().
getOperatorInfo()
Parser::OperatorInfo Cotton::Parser::getOperatorInfo (Token * token, bool is_pre_op, int special = 0)
References Cotton::OperatorNode::AND, Cotton::Token::AND_OP, Cotton::OperatorNode::ASSIGN, Cotton::Token::ASSIGN_DIV_OP, Cotton::Token::ASSIGN_MINUS_OP, Cotton::Token::ASSIGN_MULT_OP, Cotton::Token::ASSIGN_OP, Cotton::Token::ASSIGN_PLUS_OP, Cotton::Token::ASSIGN_REMAINDER_OP, Cotton::OperatorNode::AT, Cotton::Token::AT_OP, Cotton::OperatorNode::BITAND, Cotton::Token::BITAND_OP, Cotton::OperatorNode::BITOR, Cotton::Token::BITOR_OP, Cotton::OperatorNode::BITXOR, Cotton::Token::BITXOR_OP, Cotton::OperatorNode::CALL, Cotton::Token::COMMA, Cotton::OperatorNode::COMMA, Cotton::OperatorNode::DIV, Cotton::OperatorNode::DIV_ASSIGN, Cotton::Token::DIV_OP, Cotton::OperatorNode::DOT, Cotton::Token::DOT_OP, Cotton::OperatorNode::EQUAL, Cotton::Token::EQUAL_OP, Cotton::OperatorNode::GREATER, Cotton::OperatorNode::GREATER_EQUAL, Cotton::Token::GREATER_EQUAL_OP, Cotton::Token::GREATER_OP, highlight(), Cotton::Token::id, Cotton::OperatorNode::INDEX, Cotton::OperatorNode::INVERSE, Cotton::Token::INVERSE_OP, Cotton::OperatorNode::LEFT_SHIFT, Cotton::Token::LEFT_SHIFT_OP, LEFT_TO_RIGHT, Cotton::OperatorNode::LESS, Cotton::OperatorNode::LESS_EQUAL, Cotton::Token::LESS_EQUAL_OP, Cotton::Token::LESS_OP, Cotton::OperatorNode::MINUS, Cotton::OperatorNode::MINUS_ASSIGN, Cotton::Token::MINUS_MINUS_OP, Cotton::Token::MINUS_OP, Cotton::OperatorNode::MULT, Cotton::OperatorNode::MULT_ASSIGN, Cotton::Token::MULT_OP, Cotton::OperatorNode::NOT, Cotton::OperatorNode::NOT_EQUAL, Cotton::Token::NOT_EQUAL_OP, Cotton::Token::NOT_OP, Cotton::OperatorNode::OR, Cotton::Token::OR_OP, passert, Cotton::OperatorNode::PLUS, Cotton::OperatorNode::PLUS_ASSIGN, Cotton::Token::PLUS_OP, Cotton::Token::PLUS_PLUS_OP, Cotton::OperatorNode::POST_MINUS_MINUS, Cotton::OperatorNode::POST_PLUS_PLUS, Cotton::OperatorNode::PRE_MINUS, Cotton::OperatorNode::PRE_MINUS_MINUS, Cotton::OperatorNode::PRE_PLUS, Cotton::OperatorNode::PRE_PLUS_PLUS, Cotton::OperatorNode::REM, Cotton::OperatorNode::REM_ASSIGN, Cotton::Token::REMAINDER_OP, Cotton::OperatorNode::RIGHT_SHIFT, Cotton::Token::RIGHT_SHIFT_OP, RIGHT_TO_LEFT, and signalError().
Referenced by parseExpr().
goThrough()
void Cotton::Parser::goThrough (OperatorInfo op_info)
References Cotton::Parser::OperatorInfo::associativity, Cotton::Parser::ParserState::cur_associativity, Cotton::Parser::ParserState::cur_priority, Cotton::Parser::OperatorInfo::priority, and state.
Referenced by parseExpr().
hasNext()
bool Cotton::Parser::hasNext ()
References next_token, and tokens.
Referenced by parse(), parseExpr(), parseStmt(), and Cotton::skipSemicolons().
hasPrev()
bool Cotton::Parser::hasPrev ()
References next_token, and tokens.
highlight()
void Cotton::Parser::highlight (Token * token)
References state, and Cotton::Parser::ParserState::token.
Referenced by consume(), getOperatorInfo(), highlightNext(), parse(), and rollback().
highlightNext()
void Cotton::Parser::highlightNext ()
References highlight(), next_token, and tokens.
Referenced by parseExpr(), parseStmt(), and Cotton::Parser::ParsingResult::verify().
parse()
StmtNode * Cotton::Parser::parse (const std::vector< Token > & tokens)
References Cotton::Parser::ParserState::cur_associativity, Cotton::Parser::ParserState::cur_priority, EMPTY_PRIORITY, error_manager, hasNext(), highlight(), LEFT_TO_RIGHT, next_token, parseStmt(), Cotton::Parser::ParserState::report_errors, restoreState(), saveState(), Cotton::ErrorManager::setErrorCharPos(), Cotton::ErrorManager::setErrorMessage(), Cotton::skipSemicolons(), state, Cotton::Parser::ParsingResult::STMT, Cotton::Parser::ParsingResult::stmt, Cotton::Parser::ParserState::token, tokens, and Cotton::Parser::ParsingResult::verify().
Referenced by Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_smartrun(), and main().
parseExpr()
Parser::ParsingResult Cotton::Parser::parseExpr ()
References Cotton::Token::AND_OP, Cotton::Token::ASSIGN_DIV_OP, Cotton::Token::ASSIGN_MINUS_OP, Cotton::Token::ASSIGN_MULT_OP, Cotton::Token::ASSIGN_OP, Cotton::Token::ASSIGN_PLUS_OP, Cotton::Token::ASSIGN_REMAINDER_OP, Cotton::Token::AT_OP, Cotton::Token::BITAND_OP, Cotton::Token::BITOR_OP, Cotton::Token::BITXOR_OP, Cotton::Token::BOOLEAN_LIT, Cotton::Token::BREAK_KW, canPassThrough(), Cotton::Token::CHAR_LIT, checkNext(), Cotton::Token::CLOSE_BRACKET, Cotton::Token::CLOSE_CURLY_BRACKET, Cotton::Token::CLOSE_SQUARE_BRACKET, Cotton::Token::COMMA, consume(), Cotton::Token::CONTINUE_KW, Cotton::Parser::ParserState::cur_associativity, Cotton::Parser::ParserState::cur_priority, Cotton::Token::DIV_OP, Cotton::Token::DOT_OP, Cotton::Token::ELSE_KW, EMPTY_PRIORITY, Cotton::Token::EQUAL_OP, Cotton::Parser::ParsingResult::EXPR, Cotton::Token::FOR_KW, Cotton::Token::FUNCTION_KW, getOperatorInfo(), goThrough(), Cotton::Token::GREATER_EQUAL_OP, Cotton::Token::GREATER_OP, hasNext(), highlightNext(), Cotton::Parser::OperatorInfo::id, Cotton::Token::IDENTIFIER, Cotton::Token::IF_KW, Cotton::Token::INT_LIT, Cotton::Token::INVERSE_OP, Cotton::Token::LEFT_SHIFT_OP, LEFT_TO_RIGHT, Cotton::Token::LESS_EQUAL_OP, Cotton::Token::LESS_OP, Cotton::Token::METHOD_KW, Cotton::Token::MINUS_MINUS_OP, Cotton::Token::MINUS_OP, Cotton::Token::MULT_OP, next_token, Cotton::Token::NOT_EQUAL_OP, Cotton::Token::NOT_OP, Cotton::Token::NOTHING_LIT, Cotton::Token::OPEN_BRACKET, Cotton::Token::OPEN_CURLY_BRACKET, Cotton::Token::OPEN_SQUARE_BRACKET, Cotton::Token::OR_OP, parseStmt(), Cotton::Token::PLUS_OP, Cotton::Token::PLUS_PLUS_OP, POST_OP, PRE_OP, Cotton::Token::REAL_LIT, Cotton::Token::REMAINDER_OP, restoreState(), Cotton::Token::RETURN_KW, Cotton::Token::RIGHT_SHIFT_OP, saveState(), Cotton::Token::SEMICOLON, state, Cotton::Parser::ParsingResult::STMT, Cotton::Token::STRING_LIT, Cotton::Token::TYPE_KW, Cotton::Token::UNSCOPED_KW, and Cotton::Token::WHILE_KW.
Referenced by parseStmt().
parseStmt()
Parser::ParsingResult Cotton::Parser::parseStmt ()
References Cotton::StmtNode::BREAK, Cotton::Token::BREAK_KW, Cotton::Token::CLOSE_BRACKET, Cotton::Token::CLOSE_CURLY_BRACKET, Cotton::Token::CLOSE_SQUARE_BRACKET, consume(), Cotton::StmtNode::CONTINUE, Cotton::Token::CONTINUE_KW, Cotton::Token::ELSE_KW, Cotton::Parser::ParsingResult::EXPR, Cotton::Parser::ParsingResult::expr, Cotton::Token::FOR_KW, hasNext(), highlightNext(), Cotton::Token::IF_KW, next_token, Cotton::Token::OPEN_CURLY_BRACKET, parseExpr(), restoreState(), Cotton::Token::RETURN_KW, rollback(), saveState(), Cotton::Token::SEMICOLON, signalError(), Cotton::skipSemicolons(), Cotton::Parser::ParsingResult::STMT, Cotton::Token::UNSCOPED_KW, Cotton::Parser::ParsingResult::verify(), and Cotton::Token::WHILE_KW.
Referenced by parse(), and parseExpr().
restoreState()
void Cotton::Parser::restoreState ()
References saved_states, signalError(), and state.
Referenced by parse(), parseExpr(), and parseStmt().
rollback()
void Cotton::Parser::rollback ()
References highlight(), next_token, and tokens.
Referenced by parseStmt().
saveState()
void Cotton::Parser::saveState ()
References saved_states, and state.
Referenced by parse(), parseExpr(), and parseStmt().
signalError()
void Cotton::Parser::signalError (const std::string & message)
References error_manager, errors_stack, Cotton::Parser::ParserState::report_errors, Cotton::ErrorManager::signalError(), and state.
Referenced by Cotton::__passert__(), getOperatorInfo(), parseStmt(), restoreState(), and Cotton::Parser::ParsingResult::verify().
Member Data Documentation
error_manager
ErrorManager* Cotton::Parser::error_manager
Referenced by parse(), Parser(), and signalError().
errors_stack
std::vector<std::pair<ParserState, std::string> > Cotton::Parser::errors_stack
Referenced by signalError(), and Cotton::Parser::ParsingResult::verify().
next_token
std::vector<Token>::iterator Cotton::Parser::next_token
Referenced by checkNext(), consume(), hasNext(), hasPrev(), highlightNext(), parse(), parseExpr(), parseStmt(), and rollback().
saved_states
std::vector<ParserState> Cotton::Parser::saved_states
Referenced by restoreState(), and saveState().
state
ParserState Cotton::Parser::state
Referenced by canPassThrough(), goThrough(), highlight(), parse(), parseExpr(), Cotton::Parser::ParsingResult::ParsingResult(), restoreState(), saveState(), and signalError().
tokens
std::vector<Token> Cotton::Parser::tokens
Referenced by consume(), hasNext(), hasPrev(), highlightNext(), parse(), and rollback().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/front/parser.h
cotton_lib/src/cotton_lib/front/parser.cpp