Cotton::Lexer Class Reference
#include <lexer.h>
Public Member Functions
std::vector< Token > process (std::string &input)
std::vector< Token > processFile (const std::string &filename)
Lexer ()=delete
~Lexer ()=default
Lexer (ErrorManager *error_manager)
Public Attributes
ErrorManager * error_manager
Private Member Functions
void faze1FillComments (std::string &input)
std::vector< Token > faze2FormConnectedTokens (const std::string &input)
std::vector< Token > faze3SplitByOperatorsAndSeparators (const std::vector< Token > &tokens)
std::vector< Token > faze4FindRealNumbers (const std::vector< Token > &tokens)
void faze5IdentifyTokens (std::vector< Token > &tokens)
Constructor & Destructor Documentation
Lexer() [1/2]
Cotton::Lexer::Lexer () [delete]
 Lexer()
Cotton::Lexer::~Lexer () [default]
Lexer() [2/2]
Cotton::Lexer::Lexer (ErrorManager * error_manager)
References error_manager.
Member Function Documentation
faze1FillComments()
void Cotton::Lexer::faze1FillComments (std::string & input) [private]
References Cotton::skipCharacter(), and Cotton::skipString().
Referenced by process().
faze2FormConnectedTokens()
std::vector< Token > Cotton::Lexer::faze2FormConnectedTokens (const std::string & input) [private]
References Cotton::Token::CHAR_LIT, eassert, error_manager, Cotton::getCharacter(), Cotton::ErrorManager::setErrorCharPos(), and Cotton::Token::STRING_LIT.
Referenced by process().
faze3SplitByOperatorsAndSeparators()
std::vector< Token > Cotton::Lexer::faze3SplitByOperatorsAndSeparators (const std::vector< Token > & tokens) [private]
References Cotton::Token::CHAR_LIT, Cotton::sortedSplitters, Cotton::splitByOperator(), and Cotton::Token::STRING_LIT.
Referenced by process().
faze4FindRealNumbers()
std::vector< Token > Cotton::Lexer::faze4FindRealNumbers (const std::vector< Token > & tokens) [private]
References Cotton::splitByOperator().
Referenced by process().
faze5IdentifyTokens()
void Cotton::Lexer::faze5IdentifyTokens (std::vector< Token > & tokens) [private]
References error_manager.
Referenced by process().
process()
std::vector< Token > Cotton::Lexer::process (std::string & input)
References faze1FillComments(), faze2FormConnectedTokens(), faze3SplitByOperatorsAndSeparators(), faze4FindRealNumbers(), and faze5IdentifyTokens().
Referenced by Cotton::Builtin::CF_cotton(), and processFile().
processFile()
std::vector< Token > Cotton::Lexer::processFile (const std::string & filename)
References error_manager, process(), Cotton::ErrorManager::setErrorFilename(), and Cotton::ErrorManager::signalError().
Referenced by Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_smartrun(), and main().
Member Data Documentation
error_manager
ErrorManager* Cotton::Lexer::error_manager
Referenced by faze2FormConnectedTokens(), faze5IdentifyTokens(), Lexer(), processFile(), Cotton::skipCharacter(), and Cotton::skipString().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/front/lexer.h
cotton_lib/src/cotton_lib/front/lexer.cpp