Cotton::Builtin::ArrayType Class Reference
#include <array.h>
Public Member Functions
size_t getInstanceSize ()
ArrayType (Runtime *rt)
~ArrayType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
ArrayType()
Cotton::Builtin::ArrayType::ArrayType (Runtime * rt)
References Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::ArrayNeqAdapter(), Cotton::Type::eq_op, Cotton::Type::index_op, Cotton::Type::neq_op, and ProfilerCAPTURE.
 ArrayType()
Cotton::Builtin::ArrayType::~ArrayType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::ArrayType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Runtime::array_type, Cotton::Instance::copy(), Cotton::Object::instance, newObject, ProfilerCAPTURE, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::ArrayType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::ArrayType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::ArrayType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/array.h
cotton_lib/src/cotton_lib/builtin/types/array.cpp