Cotton::Parser::ParsingResult Class Reference
#include <parser.h>
Public Types
enum ResultId {
EXPR
, FUNC_DEC
, TYPE_DEF
, OPERATOR
,
ATOM
, PAR_EXPR
, IDENT_LIST
, METHOD_DEF
,
STMT
, WHILE_STMT
, FOR_STMT
, IF_STMT
,
CONTINUE_STMT
, BREAK_STMT
, RETURN_STMT
, BLOCK_STMT
 }
Public Member Functions
ParsingResult (const std::string &error_message, Parser *p)
ParsingResult (ResultId id, Parser *p)
ParsingResult (ExprNode *expr, Parser *p)
ParsingResult (FuncDefNode *func_def, Parser *p)
ParsingResult (TypeDefNode *type_def, Parser *p)
ParsingResult (OperatorNode *op, Parser *p)
ParsingResult (AtomNode *atom, Parser *p)
ParsingResult (ParExprNode *par_expr, Parser *p)
ParsingResult (IdentListNode *ident_list, Parser *p)
ParsingResult (StmtNode *stmt, Parser *p)
ParsingResult (WhileStmtNode *while_stmt, Parser *p)
ParsingResult (ForStmtNode *for_stmt, Parser *p)
ParsingResult (IfStmtNode *if_stmt, Parser *p)
ParsingResult (ReturnStmtNode *return_stmt, Parser *p)
ParsingResult (BlockStmtNode *block_stmt, Parser *p)
bool verify (Parser *p, ResultId id, const std::string error_message, bool highlight_next=true)
Public Attributes
bool success
std::string error_message
ParserState state
enum Cotton::Parser::ParsingResult::ResultId id
xx xx xx xx xx xx xx xx xx
union {
 ExprNode * expr
 FuncDefNode * func_def
 TypeDefNode * type_def
 OperatorNode * op
 AtomNode * atom
 ParExprNode * par_expr
 IdentListNode * ident_list
 FuncDefNode * method_def
 StmtNode * stmt
 WhileStmtNode * while_stmt
 ForStmtNode * for_stmt
 IfStmtNode * if_stmt
 ReturnStmtNode * return_stmt
 BlockStmtNode * block_stmt
};
Member Enumeration Documentation
ResultId
enum Cotton::Parser::ParsingResult::ResultId
Enumerator
EXPR
FUNC_DEC
TYPE_DEF
OPERATOR
ATOM
PAR_EXPR
IDENT_LIST
METHOD_DEF
STMT
WHILE_STMT
FOR_STMT
IF_STMT
CONTINUE_STMT
BREAK_STMT
RETURN_STMT
BLOCK_STMT
Constructor & Destructor Documentation
ParsingResult() [1/15]
Cotton::Parser::ParsingResult::ParsingResult (const std::string & error_message, Parser * p)
References Cotton::Parser::state.
ParsingResult() [2/15]
Cotton::Parser::ParsingResult::ParsingResult (ResultId id, Parser * p)
References Cotton::Parser::state.
ParsingResult() [3/15]
Cotton::Parser::ParsingResult::ParsingResult (ExprNode * expr, Parser * p)
References Cotton::Parser::state.
ParsingResult() [4/15]
Cotton::Parser::ParsingResult::ParsingResult (FuncDefNode * func_def, Parser * p)
References Cotton::Parser::state.
ParsingResult() [5/15]
Cotton::Parser::ParsingResult::ParsingResult (TypeDefNode * type_def, Parser * p)
References Cotton::Parser::state.
ParsingResult() [6/15]
Cotton::Parser::ParsingResult::ParsingResult (OperatorNode * op, Parser * p)
References Cotton::Parser::state.
ParsingResult() [7/15]
Cotton::Parser::ParsingResult::ParsingResult (AtomNode * atom, Parser * p)
References Cotton::Parser::state.
ParsingResult() [8/15]
Cotton::Parser::ParsingResult::ParsingResult (ParExprNode * par_expr, Parser * p)
References Cotton::Parser::state.
ParsingResult() [9/15]
Cotton::Parser::ParsingResult::ParsingResult (IdentListNode * ident_list, Parser * p)
References Cotton::Parser::state.
ParsingResult() [10/15]
Cotton::Parser::ParsingResult::ParsingResult (StmtNode * stmt, Parser * p)
References Cotton::Parser::state.
ParsingResult() [11/15]
Cotton::Parser::ParsingResult::ParsingResult (WhileStmtNode * while_stmt, Parser * p)
References Cotton::Parser::state.
ParsingResult() [12/15]
Cotton::Parser::ParsingResult::ParsingResult (ForStmtNode * for_stmt, Parser * p)
References Cotton::Parser::state.
ParsingResult() [13/15]
Cotton::Parser::ParsingResult::ParsingResult (IfStmtNode * if_stmt, Parser * p)
References Cotton::Parser::state.
ParsingResult() [14/15]
Cotton::Parser::ParsingResult::ParsingResult (ReturnStmtNode * return_stmt, Parser * p)
References Cotton::Parser::state.
ParsingResult() [15/15]
Cotton::Parser::ParsingResult::ParsingResult (BlockStmtNode * block_stmt, Parser * p)
References Cotton::Parser::state.
Member Function Documentation
verify()
bool Cotton::Parser::ParsingResult::verify (Parser * p, ResultId id, const std::string error_message, bool highlight_next = true)
References error_message, Cotton::Parser::errors_stack, Cotton::Parser::highlightNext(), Cotton::Parser::signalError(), state, and success.
Referenced by Cotton::Parser::parse(), and Cotton::Parser::parseStmt().
Member Data Documentation
union { ... }
atom
AtomNode* Cotton::Parser::ParsingResult::atom
block_stmt
BlockStmtNode* Cotton::Parser::ParsingResult::block_stmt
error_message
std::string Cotton::Parser::ParsingResult::error_message
Referenced by verify().
expr
ExprNode* Cotton::Parser::ParsingResult::expr
Referenced by Cotton::Parser::parseStmt().
for_stmt
ForStmtNode* Cotton::Parser::ParsingResult::for_stmt
func_def
FuncDefNode* Cotton::Parser::ParsingResult::func_def
id
enum Cotton::Parser::ParsingResult::ResultId Cotton::Parser::ParsingResult::id
ident_list
IdentListNode* Cotton::Parser::ParsingResult::ident_list
if_stmt
IfStmtNode* Cotton::Parser::ParsingResult::if_stmt
method_def
FuncDefNode* Cotton::Parser::ParsingResult::method_def
op
OperatorNode* Cotton::Parser::ParsingResult::op
par_expr
ParExprNode* Cotton::Parser::ParsingResult::par_expr
return_stmt
ReturnStmtNode* Cotton::Parser::ParsingResult::return_stmt
state
ParserState Cotton::Parser::ParsingResult::state
Referenced by verify().
stmt
StmtNode* Cotton::Parser::ParsingResult::stmt
Referenced by Cotton::Parser::parse().
success
bool Cotton::Parser::ParsingResult::success
Referenced by verify().
type_def
TypeDefNode* Cotton::Parser::ParsingResult::type_def
while_stmt
WhileStmtNode* Cotton::Parser::ParsingResult::while_stmt
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/front/parser.h
cotton_lib/src/cotton_lib/front/parser.cpp