Cotton::Builtin::BooleanInstance Class Reference
#include <boolean.h>
Public Member Functions
BooleanInstance (Runtime *rt)
~BooleanInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Public Attributes
bool value
Additional Inherited Members
Constructor & Destructor Documentation
BooleanInstance()
Cotton::Builtin::BooleanInstance::BooleanInstance (Runtime * rt)
References ProfilerCAPTURE, and value.
Referenced by copy(), and getSize().
 BooleanInstance()
Cotton::Builtin::BooleanInstance::~BooleanInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::BooleanInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, BooleanInstance(), Cotton::Runtime::getContext(), icast, ProfilerCAPTURE, Cotton::Runtime::signalError(), userRepr(), and value.
getSize()
size_t Cotton::Builtin::BooleanInstance::getSize () [virtual]
Implements Cotton::Instance.
References BooleanInstance(), and ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::BooleanInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE, and value.
Referenced by copy().
Member Data Documentation
value
bool Cotton::Builtin::BooleanInstance::value
Referenced by BooleanInstance(), copy(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/boolean.h
cotton_lib/src/cotton_lib/builtin/types/boolean.cpp