Cotton::Builtin::IntegerType Class Reference
#include <integer.h>
Public Member Functions
size_t getInstanceSize ()
IntegerType (Runtime *rt)
~IntegerType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
IntegerType()
Cotton::Builtin::IntegerType::IntegerType (Runtime * rt)
References Cotton::Type::add_op, Cotton::Type::bitand_op, Cotton::Type::bitor_op, Cotton::Type::bitxor_op, Cotton::Type::div_op, Cotton::Type::eq_op, Cotton::Type::geq_op, Cotton::Type::gt_op, Cotton::Builtin::IntegerAddAdapter(), Cotton::Builtin::IntegerBitandAdapter(), Cotton::Builtin::IntegerBitorAdapter(), Cotton::Builtin::IntegerBitxorAdapter(), Cotton::Builtin::IntegerDivAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::IntegerGeqAdapter(), Cotton::Builtin::IntegerGtAdapter(), Cotton::Builtin::IntegerInverseAdapter(), Cotton::Builtin::IntegerLeqAdapter(), Cotton::Builtin::IntegerLshiftAdapter(), Cotton::Builtin::IntegerLtAdapter(), Cotton::Builtin::IntegerMultAdapter(), Cotton::Builtin::IntegerNegativeAdapter(), Cotton::Builtin::IntegerNeqAdapter(), Cotton::Builtin::IntegerPositiveAdapter(), Cotton::Builtin::IntegerPostdecAdapter(), Cotton::Builtin::IntegerPostincAdapter(), Cotton::Builtin::IntegerPredecAdapter(), Cotton::Builtin::IntegerPreincAdapter(), Cotton::Builtin::IntegerRemAdapter(), Cotton::Builtin::IntegerRshiftAdapter(), Cotton::Builtin::IntegerSubAdapter(), Cotton::Type::inverse_op, Cotton::Type::leq_op, Cotton::Type::lshift_op, Cotton::Type::lt_op, Cotton::Type::mult_op, Cotton::Type::negative_op, Cotton::Type::neq_op, Cotton::Type::positive_op, Cotton::Type::postdec_op, Cotton::Type::postinc_op, Cotton::Type::predec_op, Cotton::Type::preinc_op, ProfilerCAPTURE, Cotton::Type::rem_op, Cotton::Type::rshift_op, and Cotton::Type::sub_op.
 IntegerType()
Cotton::Builtin::IntegerType::~IntegerType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::IntegerType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Instance::copy(), Cotton::Object::instance, Cotton::Runtime::integer_type, newObject, ProfilerCAPTURE, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::IntegerType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::IntegerType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::IntegerType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/integer.h
cotton_lib/src/cotton_lib/builtin/types/integer.cpp