Cotton::Builtin::FunctionInstance Class Reference
#include <function.h>
Public Member Functions
FunctionInstance (Runtime *rt)
~FunctionInstance ()
void init (bool is_internal, InternalFunction internal_ptr, FuncDefNode *cotton_ptr)
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Public Attributes
bool is_internal
InternalFunction internal_ptr
FuncDefNode * cotton_ptr
Additional Inherited Members
Constructor & Destructor Documentation
FunctionInstance()
Cotton::Builtin::FunctionInstance::FunctionInstance (Runtime * rt)
References cotton_ptr, internal_ptr, is_internal, and ProfilerCAPTURE.
Referenced by copy(), and getSize().
 FunctionInstance()
Cotton::Builtin::FunctionInstance::~FunctionInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::FunctionInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, cotton_ptr, FunctionInstance(), Cotton::Runtime::getContext(), internal_ptr, is_internal, ProfilerCAPTURE, Cotton::Runtime::signalError(), and userRepr().
getSize()
size_t Cotton::Builtin::FunctionInstance::getSize () [virtual]
Implements Cotton::Instance.
References FunctionInstance(), and ProfilerCAPTURE.
init()
void Cotton::Builtin::FunctionInstance::init (bool is_internal, InternalFunction internal_ptr, FuncDefNode * cotton_ptr)
References cotton_ptr, internal_ptr, is_internal, and ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::FunctionInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References is_internal, and ProfilerCAPTURE.
Referenced by copy().
Member Data Documentation
cotton_ptr
FuncDefNode* Cotton::Builtin::FunctionInstance::cotton_ptr
Referenced by copy(), FunctionInstance(), and init().
internal_ptr
InternalFunction Cotton::Builtin::FunctionInstance::internal_ptr
Referenced by copy(), FunctionInstance(), and init().
is_internal
bool Cotton::Builtin::FunctionInstance::is_internal
Referenced by copy(), FunctionInstance(), init(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/function.h
cotton_lib/src/cotton_lib/builtin/types/function.cpp