Cotton::ReturnStmtNode Class Reference
#include <parser.h>
Public Member Functions
ReturnStmtNode ()=delete
~ReturnStmtNode ()
ReturnStmtNode (ExprNode *value, TextArea text_area)
void print (int indent=0, int step=2)
Public Attributes
TextArea text_area
ExprNode * value
Constructor & Destructor Documentation
ReturnStmtNode() [1/2]
Cotton::ReturnStmtNode::ReturnStmtNode () [delete]
 ReturnStmtNode()
Cotton::ReturnStmtNode::~ReturnStmtNode ()
References value.
ReturnStmtNode() [2/2]
Cotton::ReturnStmtNode::ReturnStmtNode (ExprNode * value, TextArea text_area)
References text_area, and value.
Member Function Documentation
print()
void Cotton::ReturnStmtNode::print (int indent = 0, int step = 2)
References Cotton::ExprNode::print(), Cotton::printPrefix(), and value.
Referenced by Cotton::StmtNode::print().
Member Data Documentation
text_area
TextArea Cotton::ReturnStmtNode::text_area
Referenced by Cotton::Runtime::execute(), and ReturnStmtNode().
value
ExprNode* Cotton::ReturnStmtNode::value
Referenced by Cotton::Runtime::execute(), print(), ReturnStmtNode(), and ~ReturnStmtNode().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/front/parser.h
cotton_lib/src/cotton_lib/front/parser.cpp