Cotton::Builtin::NothingType Class Reference
#include <nothing.h>
Public Member Functions
size_t getInstanceSize ()
NothingType (Runtime *rt)
~NothingType ()=default
Object * create (Runtime *rt)
std::string userRepr (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
NothingType()
Cotton::Builtin::NothingType::NothingType (Runtime * rt)
References Cotton::Type::eq_op, Cotton::Type::neq_op, Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::NothingNeqAdapter(), and ProfilerCAPTURE.
 NothingType()
Cotton::Builtin::NothingType::~NothingType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::NothingType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Instance::copy(), Cotton::Object::instance, newObject, Cotton::Runtime::nothing_type, ProfilerCAPTURE, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::NothingType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::NothingType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::NothingType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/nothing.h
cotton_lib/src/cotton_lib/builtin/types/nothing.cpp