Cotton::Builtin::RecordInstance Class Reference
#include <record.h>
Public Member Functions
RecordInstance (Runtime *rt)
~RecordInstance ()
Object * selectField (int64_t id, Runtime *rt)
Selects the field given by id from the instance. By default, the instance doesn't have any fields, and therefore an error is signaled.
bool hasField (int64_t id, Runtime *rt)
Returns whether the instance has the field given by id. By default, the instance doesn't have any fields, and therefore false is returned.
void addField (int64_t id, Object *obj, Runtime *rt)
Adds the field to the instance. By default, the instance does not support the addition of new fields, and therefore nothing happens when this function is called.
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
std::vector< Object * > getGCReachable ()
Public Attributes
__gnu_pbds::cc_hash_table< int64_t, Object * > fields
int64_t nameid
Additional Inherited Members
Constructor & Destructor Documentation
RecordInstance()
Cotton::Builtin::RecordInstance::RecordInstance (Runtime * rt)
References ProfilerCAPTURE.
Referenced by getSize().
 RecordInstance()
Cotton::Builtin::RecordInstance::~RecordInstance ()
References ProfilerCAPTURE.
Member Function Documentation
addField()
void Cotton::Builtin::RecordInstance::addField (int64_t id, Object * obj, Runtime * rt) [virtual]
Adds the field to the instance. By default, the instance does not support the addition of new fields, and therefore nothing happens when this function is called.
Parameters
id id of the field.
rt The Runtime. Assumed to be valid.
Reimplemented from Cotton::Instance.
References fields, Cotton::Instance::id, and ProfilerCAPTURE.
copy()
Instance * Cotton::Builtin::RecordInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE.
getGCReachable()
std::vector< Object * > Cotton::Builtin::RecordInstance::getGCReachable () [virtual]
Reimplemented from Cotton::Instance.
References fields, and ProfilerCAPTURE.
getSize()
size_t Cotton::Builtin::RecordInstance::getSize () [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE, and RecordInstance().
hasField()
bool Cotton::Builtin::RecordInstance::hasField (int64_t id, Runtime * rt) [virtual]
Returns whether the instance has the field given by id. By default, the instance doesn't have any fields, and therefore false is returned.
Parameters
id id of the field.
rt The Runtime. Assumed to be valid.
Returns
true if the instance has the field, false otherwise.
Reimplemented from Cotton::Instance.
References fields, and ProfilerCAPTURE.
selectField()
Object * Cotton::Builtin::RecordInstance::selectField (int64_t id, Runtime * rt) [virtual]
Selects the field given by id from the instance. By default, the instance doesn't have any fields, and therefore an error is signaled.
Parameters
id id of the field. Assumed to be valid.
rt The Runtime. Assumed to be valid.
Returns
The selected field.
Reimplemented from Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, fields, Cotton::Runtime::getContext(), Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::signalError(), Cotton::NameIds::userRepr(), and userRepr().
userRepr()
std::string Cotton::Builtin::RecordInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References nameid, Cotton::Runtime::nds, ProfilerCAPTURE, and Cotton::NameIds::userRepr().
Referenced by selectField().
Member Data Documentation
fields
__gnu_pbds::cc_hash_table<int64_t, Object *> Cotton::Builtin::RecordInstance::fields
Referenced by addField(), getGCReachable(), hasField(), and selectField().
nameid
int64_t Cotton::Builtin::RecordInstance::nameid
Referenced by userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/record.h
cotton_lib/src/cotton_lib/builtin/types/record.cpp