Cotton::GC Class Reference
Garbage collector class.
#include <gc.h>
Public Member Functions
GC (GCStrategy *gc_strategy)
Construct a new GC object.
~GC ()
Destroy the GC object.
void track (Object *object)
Tracks the object;.
void track (Instance *instance, size_t bytes)
Tracks the instance;.
void track (Type *type)
Tracks the type;.
void untrack (Object *object)
Untracks the object;.
void untrack (Instance *instance)
Untracks the instance;.
void untrack (Type *type)
Unracks the type;.
void hold (Object *object)
Holds the given object. The gc will consider it as reachable even if it is not.
void release (Object *object)
Releases the held object.
void ping (Runtime *rt)
Pings the gc. If the strategy's conditions are met, a gc cycle will be ran.
void runCycle (Runtime *rt)
Runs a gc cycle.
void enable ()
Enables the gc.
void disable ()
Disables the gc. Future ping calls will not run a gc cycle.z.
Public Attributes
Runtime * rt
__gnu_pbds::gp_hash_table< Object *, bool > tracked_objects
__gnu_pbds::gp_hash_table< Object *, int64_t > held_objects
__gnu_pbds::gp_hash_table< Instance *, bool > tracked_instances
__gnu_pbds::gp_hash_table< Type *, bool > tracked_types
bool gc_mark: 1
GCStrategy * gc_strategy
bool enabled
Detailed Description
Garbage collector class.
Constructor & Destructor Documentation
GC()
Cotton::GC::GC (GCStrategy * gc_strategy)
Construct a new GC object.
Parameters
gc_strategy Garbage collection strategy. Assumed to be valid.
References enabled, gc_mark, gc_strategy, and ProfilerCAPTURE.
 GC()
Cotton::GC::~GC ()
Destroy the GC object.
References ProfilerCAPTURE, tracked_instances, tracked_objects, and tracked_types.
Member Function Documentation
disable()
void Cotton::GC::disable ()
Disables the gc. Future ping calls will not run a gc cycle.z.
References enabled, and ProfilerCAPTURE.
Referenced by disable(), and main().
enable()
void Cotton::GC::enable ()
Enables the gc.
References enabled, and ProfilerCAPTURE.
Referenced by enable(), and forceping().
hold()
void Cotton::GC::hold (Object * object)
Holds the given object. The gc will consider it as reachable even if it is not.
Parameters
object Assumed to be valid.
References held_objects, and ProfilerCAPTURE.
Referenced by Cotton::Runtime::execute(), Cotton::getList(), and Cotton::Runtime::Runtime().
ping()
void Cotton::GC::ping (Runtime * rt)
Pings the gc. If the strategy's conditions are met, a gc cycle will be ran.
Parameters
rt The Runtime. Assumed to be valid.
References Cotton::GCStrategy::acknowledgePing(), gc_strategy, and ProfilerCAPTURE.
Referenced by Cotton::Runtime::execute(), forceping(), and ping().
release()
void Cotton::GC::release (Object * object)
Releases the held object.
Parameters
object Assumed to be valid.
References held_objects, and ProfilerCAPTURE.
Referenced by Cotton::Runtime::execute().
runCycle()
void Cotton::GC::runCycle (Runtime * rt)
Runs a gc cycle.
Parameters
rt The Runtime. Assumed to be valid.
References Cotton::GCStrategy::acknowledgeEndOfCycle(), enabled, gc_mark, gc_strategy, Cotton::Runtime::globals, held_objects, Cotton::mark(), ProfilerCAPTURE, rt, Cotton::Runtime::scope, tracked_instances, tracked_objects, and tracked_types.
Referenced by Cotton::GCDefaultStrategy::checkConditions().
track() [1/3]
void Cotton::GC::track (Instance * instance, size_t bytes)
Tracks the instance;.
Parameters
instance Assumed to be valid.
bytes The size of the instance in bytes.
References Cotton::GCStrategy::acknowledgeTrack(), gc_strategy, ProfilerCAPTURE, and tracked_instances.
track() [2/3]
void Cotton::GC::track (Object * object)
Tracks the object;.
Parameters
object Assumed to be valid.
References Cotton::GCStrategy::acknowledgeTrack(), gc_strategy, ProfilerCAPTURE, and tracked_objects.
Referenced by Cotton::Instance::Instance(), Cotton::Object::Object(), and Cotton::Type::Type().
track() [3/3]
void Cotton::GC::track (Type * type)
Tracks the type;.
Parameters
type Assumed to be valid.
References Cotton::GCStrategy::acknowledgeTrack(), gc_strategy, ProfilerCAPTURE, and tracked_types.
untrack() [1/3]
void Cotton::GC::untrack (Instance * instance)
Untracks the instance;.
Parameters
instance Assumed to be valid.
References ProfilerCAPTURE, and tracked_instances.
untrack() [2/3]
void Cotton::GC::untrack (Object * object)
Untracks the object;.
Parameters
object Assumed to be valid.
References ProfilerCAPTURE, and tracked_objects.
untrack() [3/3]
void Cotton::GC::untrack (Type * type)
Unracks the type;.
Parameters
type Assumed to be valid.
References ProfilerCAPTURE, and tracked_types.
Member Data Documentation
enabled
bool Cotton::GC::enabled
Referenced by disable(), enable(), forceping(), GC(), runCycle(), and status().
gc_mark
bool Cotton::GC::gc_mark
Referenced by GC(), Cotton::Instance::Instance(), Cotton::mark(), Cotton::Object::Object(), runCycle(), and Cotton::Type::Type().
gc_strategy
GCStrategy* Cotton::GC::gc_strategy
Referenced by GC(), ping(), runCycle(), and track().
held_objects
__gnu_pbds::gp_hash_table<Object *, int64_t> Cotton::GC::held_objects
Referenced by hold(), release(), and runCycle().
rt
Runtime* Cotton::GC::rt
Referenced by runCycle(), and Cotton::Runtime::Runtime().
tracked_instances
__gnu_pbds::gp_hash_table<Instance *, bool> Cotton::GC::tracked_instances
Referenced by Cotton::GCDefaultStrategy::acknowledgeEndOfCycle(), runCycle(), track(), untrack(), and ~GC().
tracked_objects
__gnu_pbds::gp_hash_table<Object *, bool> Cotton::GC::tracked_objects
Referenced by Cotton::GCDefaultStrategy::acknowledgeEndOfCycle(), runCycle(), track(), untrack(), and ~GC().
tracked_types
__gnu_pbds::gp_hash_table<Type *, bool> Cotton::GC::tracked_types
Referenced by Cotton::GCDefaultStrategy::acknowledgeEndOfCycle(), runCycle(), track(), untrack(), and ~GC().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/back/gc.h
cotton_lib/src/cotton_lib/back/gc.cpp