Cotton::Instance Class Reference
Class representing an instance of a type.
#include <instance.h>
Public Member Functions
Instance (Runtime *rt, size_t bytes)
Construct a new Instance object.
virtual ~Instance ()=default
Destroy the Instance object.
virtual Object * selectField (int64_t id, Runtime *rt)
Selects the field given by id from the instance. By default, the instance doesn't have any fields, and therefore an error is signaled.
virtual bool hasField (int64_t id, Runtime *rt)
Returns whether the instance has the field given by id. By default, the instance doesn't have any fields, and therefore false is returned.
virtual void addField (int64_t id, Object *obj, Runtime *rt)
Adds the field to the instance. By default, the instance does not support the addition of new fields, and therefore nothing happens when this function is called.
virtual std::vector< Object * > getGCReachable ()
virtual Instance * copy (Runtime *rt)=0
virtual size_t getSize ()=0
virtual std::string userRepr (Runtime *rt)=0
virtual void spreadSingleUse ()
virtual void spreadMultiUse ()
Public Attributes
int64_t id
id of the instance
bool gc_mark: 1
gc mark of the instance
Static Public Attributes
static int64_t total_instances = 0
The total number of instances created.
Detailed Description
Class representing an instance of a type.
Constructor & Destructor Documentation
Instance()
Cotton::Instance::Instance (Runtime * rt, size_t bytes)
Construct a new Instance object.
Parameters
rt The Runtime. Assumed to be valid.
bytes Size of instance in bytes.
References Cotton::Runtime::gc, Cotton::GC::gc_mark, gc_mark, ProfilerCAPTURE, total_instances, and Cotton::GC::track().
 Instance()
virtual Cotton::Instance::~Instance () [virtual], [default]
Destroy the Instance object.
Member Function Documentation
addField()
void Cotton::Instance::addField (int64_t id, Object * obj, Runtime * rt) [virtual]
Adds the field to the instance. By default, the instance does not support the addition of new fields, and therefore nothing happens when this function is called.
Parameters
id id of the field.
rt The Runtime. Assumed to be valid.
Reimplemented in Cotton::Builtin::RecordInstance.
References ProfilerCAPTURE.
copy()
virtual Instance* Cotton::Instance::copy (Runtime * rt) [pure virtual]
Implemented in Cotton::Builtin::StringInstance, Cotton::Builtin::RecordInstance, Cotton::Builtin::RealInstance, Cotton::Builtin::NothingInstance, Cotton::Builtin::IntegerInstance, Cotton::Builtin::FunctionInstance, Cotton::Builtin::CharacterInstance, Cotton::Builtin::BooleanInstance, and Cotton::Builtin::ArrayInstance.
Referenced by Cotton::Builtin::ArrayType::copy(), Cotton::Builtin::BooleanType::copy(), Cotton::Builtin::CharacterType::copy(), Cotton::Builtin::FunctionType::copy(), Cotton::Builtin::IntegerType::copy(), Cotton::Builtin::NothingType::copy(), Cotton::Builtin::RealType::copy(), Cotton::Builtin::RecordType::copy(), and Cotton::Builtin::StringType::copy().
getGCReachable()
std::vector< Object * > Cotton::Instance::getGCReachable () [virtual]
Reimplemented in Cotton::Builtin::RecordInstance, and Cotton::Builtin::ArrayInstance.
References ProfilerCAPTURE.
Referenced by Cotton::Object::getGCReachable(), Cotton::Builtin::ArrayInstance::getGCReachable(), and Cotton::mark().
getSize()
virtual size_t Cotton::Instance::getSize () [pure virtual]
Implemented in Cotton::Builtin::StringInstance, Cotton::Builtin::RecordInstance, Cotton::Builtin::RealInstance, Cotton::Builtin::NothingInstance, Cotton::Builtin::IntegerInstance, Cotton::Builtin::FunctionInstance, Cotton::Builtin::CharacterInstance, Cotton::Builtin::BooleanInstance, and Cotton::Builtin::ArrayInstance.
Referenced by Cotton::GCDefaultStrategy::acknowledgeUntrack().
hasField()
bool Cotton::Instance::hasField (int64_t id, Runtime * rt) [virtual]
Returns whether the instance has the field given by id. By default, the instance doesn't have any fields, and therefore false is returned.
Parameters
id id of the field.
rt The Runtime. Assumed to be valid.
Returns
true if the instance has the field, false otherwise.
Reimplemented in Cotton::Builtin::RecordInstance.
References ProfilerCAPTURE.
selectField()
Object * Cotton::Instance::selectField (int64_t id, Runtime * rt) [virtual]
Selects the field given by id from the instance. By default, the instance doesn't have any fields, and therefore an error is signaled.
Parameters
id id of the field. Assumed to be valid.
rt The Runtime. Assumed to be valid.
Returns
The selected field.
Reimplemented in Cotton::Builtin::RecordInstance.
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::signalError(), and Cotton::NameIds::userRepr().
Referenced by Cotton::Runtime::execute().
spreadMultiUse()
void Cotton::Instance::spreadMultiUse () [virtual]
Reimplemented in Cotton::Builtin::ArrayInstance.
References ProfilerCAPTURE.
Referenced by Cotton::Object::spreadMultiUse().
spreadSingleUse()
void Cotton::Instance::spreadSingleUse () [virtual]
Reimplemented in Cotton::Builtin::ArrayInstance.
References ProfilerCAPTURE.
Referenced by Cotton::Object::spreadSingleUse().
userRepr()
virtual std::string Cotton::Instance::userRepr (Runtime * rt) [pure virtual]
Implemented in Cotton::Builtin::StringInstance, Cotton::Builtin::RecordInstance, Cotton::Builtin::RealInstance, Cotton::Builtin::NothingInstance, Cotton::Builtin::IntegerInstance, Cotton::Builtin::FunctionInstance, Cotton::Builtin::CharacterInstance, Cotton::Builtin::BooleanInstance, and Cotton::Builtin::ArrayInstance.
Referenced by Cotton::Object::userRepr().
Member Data Documentation
gc_mark
bool Cotton::Instance::gc_mark
gc mark of the instance
Referenced by Instance(), and Cotton::mark().
id
int64_t Cotton::Instance::id
id of the instance
Referenced by Cotton::Builtin::RecordInstance::addField().
total_instances
int64_t Cotton::Instance::total_instances = 0 [static]
The total number of instances created.
Referenced by Instance().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/back/instance.h
cotton_lib/src/cotton_lib/back/instance.cpp