Cotton::Runtime Class Reference
#include <runtime.h>
Classes
class ErrorContext
Public Types
enum BuiltinTypes {
FUNCTION_TYPE_ID = 1
, NOTHING_TYPE_ID = 2
, BOOLEAN_TYPE_ID = 3
, INTEGER_TYPE_ID = 4
,
REAL_TYPE_ID = 5
, CHARACTER_TYPE_ID = 6
, STRING_TYPE_ID = 7
, ARRAY_TYPE_ID = 8
 }
enum ObjectOptions { INSTANCE_OBJECT
, TYPE_OBJECT
 }
Public Member Functions
Runtime (GCStrategy *gc_strategy, ErrorManager *error_manager, NameIds *nds)
~Runtime ()=default
bool checkGlobal (int64_t id)
Object * getGlobal (int64_t id)
void setGlobal (int64_t id, Object *obj)
void removeGlobal (int64_t id)
void registerTypeObject (Type *type, Object *obj)
Object * getTypeObject (Type *type)
void * alloc (size_t size)
void dealloc (void *ptr, size_t size)
Object * protectedBoolean (bool val)
void newFrame (bool can_access_prev_scope=true)
void popFrame ()
void newContext ()
void popContext ()
ErrorContext & getContext ()
void signalError (const std::string &message, const TextArea &ta)
Object * execute (ExprNode *node, bool execution_result_matters)
Object * execute (FuncDefNode *node, bool execution_result_matters)
Object * execute (TypeDefNode *node, bool execution_result_matters)
Object * execute (OperatorNode *node, bool execution_result_matters)
Object * execute (AtomNode *node, bool execution_result_matters)
Object * execute (ParExprNode *node, bool execution_result_matters)
Object * execute (StmtNode *node, bool execution_result_matters)
Object * execute (WhileStmtNode *node, bool execution_result_matters)
Object * execute (ForStmtNode *node, bool execution_result_matters)
Object * execute (IfStmtNode *node, bool execution_result_matters)
Object * execute (ReturnStmtNode *node, bool execution_result_matters)
Object * execute (BlockStmtNode *node, bool execution_result_matters)
Object * make (Type *type, ObjectOptions object_opt)
Object * copy (Object *obj)
Object * runOperator (OperatorNode::OperatorId id, Object *obj, bool execution_result_matters)
Object * runOperator (OperatorNode::OperatorId id, Object *obj, Object *arg, bool execution_result_matters)
Object * runOperator (OperatorNode::OperatorId id, Object *obj, const std::vector< Object * > &args, bool execution_result_matters)
Object * runMethod (int64_t id, Object *obj, const std::vector< Object * > &args, bool execution_result_matters)
bool isValidObject (Object *obj)
bool isTypeObject (Object *obj, Type *type=NULL)
bool isInstanceObject (Object *obj, Type *type=NULL)
bool isOfType (Object *obj, BuiltinTypes type)
bool isOfType (Object *obj, Type *type)
void verifyIsValidObject (Object *obj)
void verifyIsValidObject (Object *obj, const TextArea &ta)
void verifyIsTypeObject (Object *obj, Type *type)
void verifyIsTypeObject (Object *obj, Type *type, const TextArea &ta)
void verifyIsInstanceObject (Object *obj, Type *type)
void verifyIsInstanceObject (Object *obj, Type *type, const TextArea &ta)
void verifyIsOfType (Object *obj, BuiltinTypes type)
void verifyIsOfType (Object *obj, BuiltinTypes type, const TextArea &ta)
void verifyIsOfType (Object *obj, Type *type)
void verifyIsOfType (Object *obj, Type *type, const TextArea &ta)
void verifyMinArgsAmountFunc (const std::vector< Object * > &args, int64_t amount)
void verifyMinArgsAmountFunc (const std::vector< Object * > &args, int64_t amount, const TextArea &ta)
void verifyExactArgsAmountFunc (const std::vector< Object * > &args, int64_t amount)
void verifyExactArgsAmountFunc (const std::vector< Object * > &args, int64_t amount, const TextArea &ta)
void verifyMinArgsAmountMethod (const std::vector< Object * > &args, int64_t amount)
void verifyMinArgsAmountMethod (const std::vector< Object * > &args, int64_t amount, const TextArea &ta)
void verifyExactArgsAmountMethod (const std::vector< Object * > &args, int64_t amount)
void verifyExactArgsAmountMethod (const std::vector< Object * > &args, int64_t amount, const TextArea &ta)
void verifyHasMethod (Object *obj, int64_t id)
void verifyHasMethod (Object *obj, int64_t id, const TextArea &ta)
Public Attributes
Builtin::FunctionType * function_type
Builtin::NothingType * nothing_type
Builtin::BooleanType * boolean_type
Builtin::IntegerType * integer_type
Builtin::RealType * real_type
Builtin::CharacterType * character_type
Builtin::StringType * string_type
Builtin::ArrayType * array_type
__gnu_pbds::cc_hash_table< int64_t, Object * > globals
__gnu_pbds::cc_hash_table< Type *, Object * > type_objects
NameIds * nds
Object * exec_res_default
__gnu_pbds::cc_hash_table< int64_t, Object * > readonly_literals
Object * protected_nothing
Object * protected_true
Object * protected_false
Scope * scope
GC * gc
ErrorManager * error_manager
std::vector< ErrorContext > error_contexts
uint8_t execution_flags
Member Enumeration Documentation
BuiltinTypes
enum Cotton::Runtime::BuiltinTypes
Enumerator
FUNCTION_TYPE_ID
NOTHING_TYPE_ID
BOOLEAN_TYPE_ID
INTEGER_TYPE_ID
REAL_TYPE_ID
CHARACTER_TYPE_ID
STRING_TYPE_ID
ARRAY_TYPE_ID
ObjectOptions
enum Cotton::Runtime::ObjectOptions
Enumerator
INSTANCE_OBJECT
TYPE_OBJECT
Constructor & Destructor Documentation
Runtime()
Cotton::Runtime::Runtime (GCStrategy * gc_strategy, ErrorManager * error_manager, NameIds * nds)
References Cotton::Scope::addVariable(), array_type, ARRAY_TYPE_ID, boolean_type, BOOLEAN_TYPE_ID, Cotton::Object::can_modify, character_type, CHARACTER_TYPE_ID, error_manager, function_type, FUNCTION_TYPE_ID, gc, Cotton::NameIds::get(), Cotton::Builtin::getBooleanValue(), Cotton::GC::hold(), Cotton::NameId::id, Cotton::Type::id, Cotton::Builtin::installArrayMethods(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installBuiltinFunctions(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installFunctionMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installNothingMethods(), Cotton::Builtin::installRealMethods(), Cotton::Builtin::installStringMethods(), INSTANCE_OBJECT, integer_type, INTEGER_TYPE_ID, make(), Cotton::Scope::master, nds, newContext(), nothing_type, NOTHING_TYPE_ID, ProfilerCAPTURE, protected_false, protected_nothing, protected_true, real_type, REAL_TYPE_ID, registerTypeObject(), Cotton::GC::rt, scope, string_type, STRING_TYPE_ID, and TYPE_OBJECT.
 Runtime()
Cotton::Runtime::~Runtime () [default]
Member Function Documentation
alloc()
void* Cotton::Runtime::alloc (size_t size)
checkGlobal()
bool Cotton::Runtime::checkGlobal (int64_t id)
References globals.
Referenced by Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_loadlibrary(), and Cotton::Builtin::CF_smartrun().
copy()
Object * Cotton::Runtime::copy (Object * obj)
References Cotton::Type::copy(), isValidObject(), ProfilerCAPTURE, signalError(), Cotton::Object::single_use, Cotton::Object::type, and Cotton::Object::userRepr().
Referenced by Cotton::Object::assignToCopyOf(), Cotton::Builtin::CF_copy(), Cotton::Builtin::ArrayInstance::copy(), execute(), Cotton::getList(), and Cotton::Builtin::StringAddAdapter().
dealloc()
void Cotton::Runtime::dealloc (void * ptr, size_t size)
execute() [1/12]
Object * Cotton::Runtime::execute (AtomNode * node, bool execution_result_matters)
References Cotton::Runtime::ErrorContext::area, Cotton::AtomNode::bool_value, Cotton::AtomNode::BOOLEAN, Cotton::AtomNode::char_value, Cotton::AtomNode::CHARACTER, gc, getContext(), Cotton::Scope::getVariable(), Cotton::GC::hold(), Cotton::AtomNode::id, Cotton::AtomNode::IDENTIFIER, Cotton::AtomNode::int_value, Cotton::AtomNode::INTEGER, Cotton::AtomNode::lit_obj, Cotton::Builtin::makeBooleanInstanceObject(), Cotton::Builtin::makeCharacterInstanceObject(), Cotton::Builtin::makeIntegerInstanceObject(), Cotton::Builtin::makeNothingInstanceObject(), Cotton::Builtin::makeRealInstanceObject(), Cotton::Builtin::makeStringInstanceObject(), Cotton::Token::nameid, newContext(), Cotton::AtomNode::NOTHING, popContext(), ProfilerCAPTURE, readonly_literals, Cotton::AtomNode::REAL, Cotton::AtomNode::real_value, scope, setExecFlagNONE, signalError(), Cotton::AtomNode::STRING, Cotton::AtomNode::string_value, Cotton::AtomNode::text_area, and Cotton::AtomNode::token.
execute() [2/12]
Object * Cotton::Runtime::execute (BlockStmtNode * node, bool execution_result_matters)
References Cotton::Runtime::ErrorContext::area, execute(), getContext(), Cotton::BlockStmtNode::is_unscoped, isExecFlagNONE, Cotton::BlockStmtNode::list, newContext(), newFrame(), popContext(), popFrame(), ProfilerCAPTURE, protected_nothing, setExecFlagNONE, signalError(), and Cotton::BlockStmtNode::text_area.
execute() [3/12]
Object * Cotton::Runtime::execute (ExprNode * node, bool execution_result_matters)
References Cotton::ExprNode::ATOM, Cotton::ExprNode::atom, Cotton::ExprNode::func_def, Cotton::ExprNode::FUNCTION_DEFINITION, getContext(), Cotton::ExprNode::id, Cotton::ExprNode::op, Cotton::ExprNode::OPERATOR, Cotton::ExprNode::par_expr, Cotton::ExprNode::PARENTHESES_EXPRESSION, ProfilerCAPTURE, signalError(), Cotton::ExprNode::type_def, and Cotton::ExprNode::TYPE_DEFINITION.
Referenced by Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_smartrun(), execute(), Cotton::Builtin::FunctionCallAdapter(), Cotton::getList(), and main().
execute() [4/12]
Object * Cotton::Runtime::execute (ForStmtNode * node, bool execution_result_matters)
References Cotton::Runtime::ErrorContext::area, Cotton::ForStmtNode::body, Cotton::ForStmtNode::cond, copy(), execute(), Cotton::Builtin::getBooleanValue(), getContext(), Cotton::ForStmtNode::init, isExecFlagBREAK, isExecFlagCONTINUE, isExecFlagDIRECT_PASS, isExecFlagRETURN, newContext(), newFrame(), popContext(), popFrame(), ProfilerCAPTURE, protected_nothing, setExecFlagNONE, setExecFlagRETURN, signalError(), Cotton::ForStmtNode::step, Cotton::ExprNode::text_area, Cotton::StmtNode::text_area, and Cotton::ForStmtNode::text_area.
execute() [5/12]
Object * Cotton::Runtime::execute (FuncDefNode * node, bool execution_result_matters)
References Cotton::Scope::addVariable(), Cotton::Runtime::ErrorContext::area, getContext(), Cotton::Builtin::makeFunctionInstanceObject(), Cotton::FuncDefNode::name, Cotton::Token::nameid, newContext(), popContext(), ProfilerCAPTURE, scope, setExecFlagNONE, signalError(), and Cotton::FuncDefNode::text_area.
execute() [6/12]
Object * Cotton::Runtime::execute (IfStmtNode * node, bool execution_result_matters)
References Cotton::Runtime::ErrorContext::area, Cotton::IfStmtNode::body, Cotton::IfStmtNode::cond, Cotton::IfStmtNode::else_body, execute(), Cotton::Builtin::getBooleanValue(), getContext(), newContext(), popContext(), ProfilerCAPTURE, protected_nothing, setExecFlagNONE, signalError(), and Cotton::ExprNode::text_area.
execute() [7/12]
Object * Cotton::Runtime::execute (OperatorNode * node, bool execution_result_matters)
References Cotton::Scope::addVariable(), Cotton::Runtime::ErrorContext::area, Cotton::OperatorNode::ASSIGN, Cotton::OperatorNode::AT, Cotton::ExprNode::ATOM, Cotton::ExprNode::atom, Cotton::OperatorNode::CALL, Cotton::OperatorNode::COMMA, Cotton::OperatorNode::DIV, Cotton::OperatorNode::DIV_ASSIGN, Cotton::OperatorNode::DOT, execute(), Cotton::OperatorNode::first, gc, getContext(), Cotton::getList(), Cotton::getList_addToContext(), Cotton::Type::getMethod(), Cotton::GC::hold(), Cotton::ExprNode::id, Cotton::OperatorNode::id, Cotton::AtomNode::id, Cotton::AtomNode::ident, Cotton::AtomNode::IDENTIFIER, Cotton::OperatorNode::INDEX, Cotton::Object::instance, Cotton::OperatorNode::INVERSE, isExecFlagDIRECT_PASS, isInstanceObject(), Cotton::Builtin::makeNothingInstanceObject(), Cotton::OperatorNode::MINUS, Cotton::OperatorNode::MINUS_ASSIGN, Cotton::OperatorNode::MULT, Cotton::OperatorNode::MULT_ASSIGN, Cotton::Token::nameid, newContext(), Cotton::OperatorNode::NOT, Cotton::ExprNode::op, Cotton::ExprNode::OPERATOR, Cotton::OperatorNode::PLUS, Cotton::OperatorNode::PLUS_ASSIGN, popContext(), Cotton::OperatorNode::POST_MINUS_MINUS, Cotton::OperatorNode::POST_PLUS_PLUS, Cotton::OperatorNode::PRE_MINUS, Cotton::OperatorNode::PRE_MINUS_MINUS, Cotton::OperatorNode::PRE_PLUS, Cotton::OperatorNode::PRE_PLUS_PLUS, ProfilerCAPTURE, Cotton::Scope::queryVariable(), Cotton::GC::release(), Cotton::OperatorNode::REM, Cotton::OperatorNode::REM_ASSIGN, runOperator(), scope, Cotton::OperatorNode::second, Cotton::Instance::selectField(), setExecFlagDIRECT_PASS, setExecFlagNONE, signalError(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::ExprNode::text_area, Cotton::OperatorNode::text_area, and Cotton::Object::type.
execute() [8/12]
Object * Cotton::Runtime::execute (ParExprNode * node, bool execution_result_matters)
References execute(), Cotton::ParExprNode::expr, getContext(), ProfilerCAPTURE, and signalError().
execute() [9/12]
Object * Cotton::Runtime::execute (ReturnStmtNode * node, bool execution_result_matters)
References Cotton::Runtime::ErrorContext::area, copy(), execute(), getContext(), isExecFlagDIRECT_PASS, newContext(), popContext(), ProfilerCAPTURE, setExecFlagRETURN, signalError(), Cotton::ReturnStmtNode::text_area, and Cotton::ReturnStmtNode::value.
execute() [10/12]
Object * Cotton::Runtime::execute (StmtNode * node, bool execution_result_matters)
References Cotton::StmtNode::BLOCK, Cotton::StmtNode::block_stmt, Cotton::StmtNode::BREAK, Cotton::StmtNode::CONTINUE, execute(), Cotton::StmtNode::EXPR, Cotton::StmtNode::expr, Cotton::StmtNode::FOR, Cotton::StmtNode::for_stmt, gc, getContext(), Cotton::StmtNode::id, Cotton::StmtNode::IF, Cotton::StmtNode::if_stmt, Cotton::GC::ping(), ProfilerCAPTURE, protected_nothing, Cotton::StmtNode::RETURN, Cotton::StmtNode::return_stmt, setExecFlagBREAK, setExecFlagCONTINUE, signalError(), Cotton::StmtNode::text_area, Cotton::StmtNode::WHILE, and Cotton::StmtNode::while_stmt.
execute() [11/12]
Object * Cotton::Runtime::execute (TypeDefNode * node, bool execution_result_matters)
References Cotton::Scope::addVariable(), Cotton::Runtime::ErrorContext::area, Cotton::TypeDefNode::fields, Cotton::NameIds::get(), getContext(), Cotton::NameId::id, make(), Cotton::Builtin::makeFunctionInstanceObject(), Cotton::TypeDefNode::methods, Cotton::TypeDefNode::name, Cotton::Token::nameid, nds, newContext(), popContext(), ProfilerCAPTURE, scope, setExecFlagNONE, signalError(), Cotton::TypeDefNode::text_area, and TYPE_OBJECT.
execute() [12/12]
Object * Cotton::Runtime::execute (WhileStmtNode * node, bool execution_result_matters)
References Cotton::Runtime::ErrorContext::area, Cotton::WhileStmtNode::body, Cotton::WhileStmtNode::cond, copy(), execute(), Cotton::Builtin::getBooleanValue(), getContext(), isExecFlagBREAK, isExecFlagCONTINUE, isExecFlagDIRECT_PASS, isExecFlagRETURN, newContext(), newFrame(), popContext(), popFrame(), ProfilerCAPTURE, protected_nothing, setExecFlagNONE, setExecFlagRETURN, signalError(), Cotton::ExprNode::text_area, Cotton::StmtNode::text_area, and Cotton::WhileStmtNode::text_area.
getContext()
Runtime::ErrorContext & Cotton::Runtime::getContext ()
References error_contexts, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::arrayResizeMethod(), Cotton::Builtin::arraySizeMethod(), Cotton::Object::assignTo(), Cotton::Object::assignToCopyOf(), Cotton::Builtin::BooleanAndAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::BooleanNotAdapter(), Cotton::Builtin::BooleanOrAdapter(), Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_assert(), Cotton::Builtin::CF_bool(), Cotton::Builtin::CF_char(), Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_copy(), Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_error(), Cotton::Builtin::CF_exit(), Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_int(), Cotton::Builtin::CF_isinsobj(), Cotton::Builtin::CF_istypeobj(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_make(), Cotton::Builtin::CF_print(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_read(), Cotton::Builtin::CF_real(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_repr(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_sleep(), Cotton::Builtin::CF_smartrun(), Cotton::Builtin::CF_string(), Cotton::Builtin::CF_system(), Cotton::Builtin::CF_typeof(), Cotton::Builtin::CharacterAddAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::CharacterGeqAdapter(), Cotton::Builtin::CharacterGtAdapter(), Cotton::Builtin::CharacterLeqAdapter(), Cotton::Builtin::CharacterLtAdapter(), Cotton::Builtin::CharacterNegativeAdapter(), Cotton::Builtin::CharacterPositiveAdapter(), Cotton::Builtin::CharacterPostdecAdapter(), Cotton::Builtin::CharacterPostincAdapter(), Cotton::Builtin::CharacterPredecAdapter(), Cotton::Builtin::CharacterPreincAdapter(), Cotton::Builtin::CharacterSubAdapter(), Cotton::Builtin::ArrayInstance::copy(), Cotton::Builtin::BooleanInstance::copy(), Cotton::Builtin::CharacterInstance::copy(), Cotton::Builtin::FunctionInstance::copy(), Cotton::Builtin::IntegerInstance::copy(), Cotton::Builtin::NothingInstance::copy(), Cotton::Builtin::RealInstance::copy(), Cotton::Builtin::StringInstance::copy(), execute(), Cotton::Builtin::FunctionCallAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::getCharacterValue(), Cotton::getList(), Cotton::getList_addToContext(), Cotton::Type::getMethod(), Cotton::Builtin::getRealValue(), Cotton::Scope::getVariable(), Cotton::Builtin::IntegerAddAdapter(), Cotton::Builtin::IntegerBitandAdapter(), Cotton::Builtin::IntegerBitorAdapter(), Cotton::Builtin::IntegerBitxorAdapter(), Cotton::Builtin::IntegerDivAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::IntegerGeqAdapter(), Cotton::Builtin::IntegerGtAdapter(), Cotton::Builtin::IntegerInverseAdapter(), Cotton::Builtin::IntegerLeqAdapter(), Cotton::Builtin::IntegerLshiftAdapter(), Cotton::Builtin::IntegerLtAdapter(), Cotton::Builtin::IntegerMultAdapter(), Cotton::Builtin::IntegerNegativeAdapter(), Cotton::Builtin::IntegerPositiveAdapter(), Cotton::Builtin::IntegerPostdecAdapter(), Cotton::Builtin::IntegerPostincAdapter(), Cotton::Builtin::IntegerPredecAdapter(), Cotton::Builtin::IntegerPreincAdapter(), Cotton::Builtin::IntegerRemAdapter(), Cotton::Builtin::IntegerRshiftAdapter(), Cotton::Builtin::IntegerSubAdapter(), make(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::RealAddAdapter(), Cotton::Builtin::RealDivAdapter(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::RealGeqAdapter(), Cotton::Builtin::RealGtAdapter(), Cotton::Builtin::RealLeqAdapter(), Cotton::Builtin::RealLtAdapter(), Cotton::Builtin::RealMultAdapter(), Cotton::Builtin::RealNegativeAdapter(), Cotton::Builtin::RealPositiveAdapter(), Cotton::Builtin::RealSubAdapter(), runOperator(), Cotton::Instance::selectField(), Cotton::Builtin::RecordInstance::selectField(), Cotton::Builtin::StringAddAdapter(), Cotton::Builtin::StringEqAdapter(), Cotton::Builtin::StringIndexAdapter(), Cotton::Builtin::stringSetMethod(), Cotton::Builtin::stringSizeMethod(), and verifyMinArgsAmountMethod().
getGlobal()
Object * Cotton::Runtime::getGlobal (int64_t id)
References Cotton::NameIds::fromId(), globals, nds, ProfilerCAPTURE, and signalError().
Referenced by Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_loadlibrary(), and Cotton::Builtin::CF_smartrun().
getTypeObject()
Object * Cotton::Runtime::getTypeObject (Type * type)
References ProfilerCAPTURE, protected_nothing, and type_objects.
Referenced by Cotton::Builtin::CF_typeof().
isInstanceObject()
bool Cotton::Runtime::isInstanceObject (Object * obj, Type * type = NULL)
References Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Object::type.
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::CF_isinsobj(), Cotton::Builtin::CF_istypeobj(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CharacterEqAdapter(), execute(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::StringEqAdapter(), and verifyIsInstanceObject().
isOfType() [1/2]
bool Cotton::Runtime::isOfType (Object * obj, BuiltinTypes type)
References array_type, ARRAY_TYPE_ID, boolean_type, BOOLEAN_TYPE_ID, character_type, CHARACTER_TYPE_ID, function_type, FUNCTION_TYPE_ID, integer_type, INTEGER_TYPE_ID, nothing_type, NOTHING_TYPE_ID, ProfilerCAPTURE, real_type, REAL_TYPE_ID, string_type, STRING_TYPE_ID, and Cotton::Object::type.
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::StringEqAdapter(), and verifyIsOfType().
isOfType() [2/2]
bool Cotton::Runtime::isOfType (Object * obj, Type * type)
References ProfilerCAPTURE, and Cotton::Object::type.
isTypeObject()
bool Cotton::Runtime::isTypeObject (Object * obj, Type * type = NULL)
References Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Object::type.
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::StringEqAdapter(), and verifyIsTypeObject().
isValidObject()
bool Cotton::Runtime::isValidObject (Object * obj)
References ProfilerCAPTURE, and Cotton::Object::type.
Referenced by Cotton::Builtin::CF_make(), copy(), main(), and verifyIsValidObject().
make()
Object * Cotton::Runtime::make (Type * type, ObjectOptions object_opt)
References Cotton::Type::create(), getContext(), INSTANCE_OBJECT, newObject, ProfilerCAPTURE, signalError(), Cotton::Object::spreadSingleUse(), and Cotton::Type::userRepr().
Referenced by Cotton::Builtin::CF_make(), execute(), library_load_point(), Cotton::Builtin::makeArrayInstanceObject(), Cotton::Builtin::makeBooleanInstanceObject(), Cotton::Builtin::makeCharacterInstanceObject(), Cotton::Builtin::makeFunctionInstanceObject(), Cotton::Builtin::makeIntegerInstanceObject(), Cotton::Builtin::makeNothingInstanceObject(), Cotton::Builtin::makeRealInstanceObject(), Cotton::Builtin::makeRecordInstanceObject(), Cotton::Builtin::makeStringInstanceObject(), and Runtime().
newContext()
void Cotton::Runtime::newContext ()
References error_contexts, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::CF_print(), Cotton::Builtin::CF_printraw(), execute(), Cotton::getList(), and Runtime().
newFrame()
void Cotton::Runtime::newFrame (bool can_access_prev_scope = true)
References Cotton::Scope::master, ProfilerCAPTURE, and scope.
Referenced by Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_smartrun(), execute(), and Cotton::Builtin::FunctionCallAdapter().
popContext()
void Cotton::Runtime::popContext ()
References error_contexts, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::CF_print(), Cotton::Builtin::CF_printraw(), execute(), and Cotton::getList().
popFrame()
void Cotton::Runtime::popFrame ()
References Cotton::Scope::prev, ProfilerCAPTURE, and scope.
Referenced by Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_smartrun(), execute(), and Cotton::Builtin::FunctionCallAdapter().
protectedBoolean()
Object * Cotton::Runtime::protectedBoolean (bool val)
References ProfilerCAPTURE, protected_false, and protected_true.
Referenced by Cotton::Builtin::BooleanAndAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::BooleanOrAdapter(), Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_isinsobj(), Cotton::Builtin::CF_istypeobj(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::CharacterGeqAdapter(), Cotton::Builtin::CharacterGtAdapter(), Cotton::Builtin::CharacterLeqAdapter(), Cotton::Builtin::CharacterLtAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::IntegerGeqAdapter(), Cotton::Builtin::IntegerGtAdapter(), Cotton::Builtin::IntegerLeqAdapter(), Cotton::Builtin::IntegerLtAdapter(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::RealGeqAdapter(), Cotton::Builtin::RealGtAdapter(), Cotton::Builtin::RealLeqAdapter(), Cotton::Builtin::RealLtAdapter(), status(), and Cotton::Builtin::StringEqAdapter().
registerTypeObject()
void Cotton::Runtime::registerTypeObject (Type * type, Object * obj)
References ProfilerCAPTURE, and type_objects.
Referenced by Runtime().
removeGlobal()
void Cotton::Runtime::removeGlobal (int64_t id)
References globals, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_removeglobal().
runMethod()
Object * Cotton::Runtime::runMethod (int64_t id, Object * obj, const std::vector< Object * > & args, bool execution_result_matters)
References Cotton::OperatorNode::CALL, Cotton::Type::getMethod(), ProfilerCAPTURE, runOperator(), and Cotton::Object::type.
Referenced by Cotton::Builtin::CF_bool(), Cotton::Builtin::CF_char(), Cotton::Builtin::CF_copy(), Cotton::Builtin::CF_int(), Cotton::Builtin::CF_make(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_read(), Cotton::Builtin::CF_real(), Cotton::Builtin::CF_repr(), Cotton::Builtin::CF_string(), and Cotton::Builtin::mm__repr__().
runOperator() [1/3]
Object * Cotton::Runtime::runOperator (OperatorNode::OperatorId id, Object * obj, bool execution_result_matters)
References getContext(), Cotton::OperatorNode::INVERSE, Cotton::Type::inverse_op, Cotton::Type::negative_op, Cotton::OperatorNode::NOT, Cotton::Type::not_op, Cotton::Type::positive_op, Cotton::OperatorNode::POST_MINUS_MINUS, Cotton::OperatorNode::POST_PLUS_PLUS, Cotton::Type::postdec_op, Cotton::Type::postinc_op, Cotton::OperatorNode::PRE_MINUS, Cotton::OperatorNode::PRE_MINUS_MINUS, Cotton::OperatorNode::PRE_PLUS, Cotton::OperatorNode::PRE_PLUS_PLUS, Cotton::Type::predec_op, Cotton::Type::preinc_op, ProfilerCAPTURE, signalError(), Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsValidObject().
Referenced by Cotton::Builtin::ArrayEqAdapter(), execute(), and runMethod().
runOperator() [2/3]
Object * Cotton::Runtime::runOperator (OperatorNode::OperatorId id, Object * obj, const std::vector< Object * > & args, bool execution_result_matters)
References Cotton::OperatorNode::CALL, Cotton::Type::call_op, getContext(), Cotton::OperatorNode::INDEX, Cotton::Type::index_op, ProfilerCAPTURE, signalError(), Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsValidObject().
runOperator() [3/3]
Object * Cotton::Runtime::runOperator (OperatorNode::OperatorId id, Object * obj, Object * arg, bool execution_result_matters)
References Cotton::Type::add_op, Cotton::OperatorNode::AND, Cotton::Type::and_op, Cotton::OperatorNode::BITAND, Cotton::Type::bitand_op, Cotton::OperatorNode::BITOR, Cotton::Type::bitor_op, Cotton::OperatorNode::BITXOR, Cotton::Type::bitxor_op, Cotton::OperatorNode::DIV, Cotton::Type::div_op, Cotton::Type::eq_op, Cotton::OperatorNode::EQUAL, Cotton::Type::geq_op, getContext(), Cotton::OperatorNode::GREATER, Cotton::OperatorNode::GREATER_EQUAL, Cotton::Type::gt_op, Cotton::OperatorNode::LEFT_SHIFT, Cotton::Type::leq_op, Cotton::OperatorNode::LESS, Cotton::OperatorNode::LESS_EQUAL, Cotton::Type::lshift_op, Cotton::Type::lt_op, Cotton::OperatorNode::MINUS, Cotton::OperatorNode::MULT, Cotton::Type::mult_op, Cotton::Type::neq_op, Cotton::OperatorNode::NOT_EQUAL, Cotton::OperatorNode::OR, Cotton::Type::or_op, Cotton::OperatorNode::PLUS, ProfilerCAPTURE, Cotton::OperatorNode::REM, Cotton::Type::rem_op, Cotton::OperatorNode::RIGHT_SHIFT, Cotton::Type::rshift_op, signalError(), Cotton::Type::sub_op, Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsValidObject().
setGlobal()
void Cotton::Runtime::setGlobal (int64_t id, Object * obj)
References globals, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_setglobal(), and Cotton::Builtin::CF_smartrun().
signalError()
void Cotton::Runtime::signalError (const std::string & message, const TextArea & ta)
References error_contexts, error_manager, Cotton::TextArea::first_char, Cotton::TextArea::last_char, ProfilerCAPTURE, and Cotton::ErrorManager::signalError().
Referenced by Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::arrayResizeMethod(), Cotton::Object::assignTo(), Cotton::Object::assignToCopyOf(), Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_assert(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_error(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_smartrun(), copy(), Cotton::Builtin::ArrayInstance::copy(), Cotton::Builtin::BooleanInstance::copy(), Cotton::Builtin::CharacterInstance::copy(), Cotton::Builtin::FunctionInstance::copy(), Cotton::Builtin::IntegerInstance::copy(), Cotton::Builtin::NothingInstance::copy(), Cotton::Builtin::RealInstance::copy(), Cotton::Builtin::StringInstance::copy(), execute(), Cotton::Builtin::FunctionCallAdapter(), getGlobal(), Cotton::Type::getMethod(), Cotton::Scope::getVariable(), make(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__read__(), runOperator(), Cotton::Instance::selectField(), Cotton::Builtin::RecordInstance::selectField(), Cotton::Builtin::StringIndexAdapter(), Cotton::Builtin::stringSetMethod(), verifyExactArgsAmountFunc(), verifyExactArgsAmountMethod(), verifyHasMethod(), verifyIsInstanceObject(), verifyIsOfType(), verifyIsTypeObject(), verifyIsValidObject(), verifyMinArgsAmountFunc(), and verifyMinArgsAmountMethod().
verifyExactArgsAmountFunc() [1/2]
void Cotton::Runtime::verifyExactArgsAmountFunc (const std::vector< Object * > & args, int64_t amount)
References ProfilerCAPTURE, and signalError().
Referenced by Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::CF_argc(), Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_argv(), Cotton::Builtin::CF_bool(), Cotton::Builtin::CF_char(), Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_copy(), Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_error(), Cotton::Builtin::CF_exit(), Cotton::Builtin::CF_fork(), Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_int(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_make(), Cotton::Builtin::CF_read(), Cotton::Builtin::CF_readln(), Cotton::Builtin::CF_readraw(), Cotton::Builtin::CF_real(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_repr(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_sleep(), Cotton::Builtin::CF_smartrun(), Cotton::Builtin::CF_string(), Cotton::Builtin::CF_system(), Cotton::Builtin::CF_typeof(), and Cotton::Builtin::StringIndexAdapter().
verifyExactArgsAmountFunc() [2/2]
void Cotton::Runtime::verifyExactArgsAmountFunc (const std::vector< Object * > & args, int64_t amount, const TextArea & ta)
References ProfilerCAPTURE, and signalError().
verifyExactArgsAmountMethod() [1/2]
void Cotton::Runtime::verifyExactArgsAmountMethod (const std::vector< Object * > & args, int64_t amount)
References ProfilerCAPTURE, and signalError().
Referenced by Cotton::Builtin::arrayResizeMethod(), Cotton::Builtin::arraySizeMethod(), disable(), enable(), forceping(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), ping(), status(), Cotton::Builtin::stringSetMethod(), and Cotton::Builtin::stringSizeMethod().
verifyExactArgsAmountMethod() [2/2]
void Cotton::Runtime::verifyExactArgsAmountMethod (const std::vector< Object * > & args, int64_t amount, const TextArea & ta)
References ProfilerCAPTURE, and signalError().
verifyHasMethod() [1/2]
void Cotton::Runtime::verifyHasMethod (Object * obj, int64_t id)
References Cotton::Type::hasMethod(), ProfilerCAPTURE, signalError(), Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsInstanceObject().
Referenced by Cotton::Builtin::CF_bool(), Cotton::Builtin::CF_char(), Cotton::Builtin::CF_int(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_read(), Cotton::Builtin::CF_real(), Cotton::Builtin::CF_repr(), and Cotton::Builtin::CF_string().
verifyHasMethod() [2/2]
void Cotton::Runtime::verifyHasMethod (Object * obj, int64_t id, const TextArea & ta)
References Cotton::Type::hasMethod(), ProfilerCAPTURE, signalError(), Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsValidObject().
verifyIsInstanceObject() [1/2]
void Cotton::Runtime::verifyIsInstanceObject (Object * obj, Type * type)
References isInstanceObject(), ProfilerCAPTURE, signalError(), Cotton::Object::userRepr(), and Cotton::Type::userRepr().
Referenced by Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::arrayResizeMethod(), Cotton::Builtin::arraySizeMethod(), Cotton::Builtin::BooleanAndAdapter(), Cotton::Builtin::BooleanNotAdapter(), Cotton::Builtin::BooleanOrAdapter(), Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_assert(), Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_error(), Cotton::Builtin::CF_exit(), Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_sleep(), Cotton::Builtin::CF_smartrun(), Cotton::Builtin::CF_system(), Cotton::Builtin::CharacterAddAdapter(), Cotton::Builtin::CharacterGeqAdapter(), Cotton::Builtin::CharacterGtAdapter(), Cotton::Builtin::CharacterLeqAdapter(), Cotton::Builtin::CharacterLtAdapter(), Cotton::Builtin::CharacterNegativeAdapter(), Cotton::Builtin::CharacterPositiveAdapter(), Cotton::Builtin::CharacterPostdecAdapter(), Cotton::Builtin::CharacterPostincAdapter(), Cotton::Builtin::CharacterPredecAdapter(), Cotton::Builtin::CharacterPreincAdapter(), Cotton::Builtin::CharacterSubAdapter(), Cotton::Builtin::FunctionCallAdapter(), Cotton::Builtin::getArrayData(), Cotton::Builtin::getBooleanValue(), Cotton::Builtin::getCharacterValue(), Cotton::Builtin::getIntegerValue(), Cotton::Builtin::getRealValue(), Cotton::Builtin::getStringData(), Cotton::Builtin::IntegerAddAdapter(), Cotton::Builtin::IntegerBitandAdapter(), Cotton::Builtin::IntegerBitorAdapter(), Cotton::Builtin::IntegerBitxorAdapter(), Cotton::Builtin::IntegerDivAdapter(), Cotton::Builtin::IntegerGeqAdapter(), Cotton::Builtin::IntegerGtAdapter(), Cotton::Builtin::IntegerInverseAdapter(), Cotton::Builtin::IntegerLeqAdapter(), Cotton::Builtin::IntegerLshiftAdapter(), Cotton::Builtin::IntegerLtAdapter(), Cotton::Builtin::IntegerMultAdapter(), Cotton::Builtin::IntegerNegativeAdapter(), Cotton::Builtin::IntegerPositiveAdapter(), Cotton::Builtin::IntegerPostdecAdapter(), Cotton::Builtin::IntegerPostincAdapter(), Cotton::Builtin::IntegerPredecAdapter(), Cotton::Builtin::IntegerPreincAdapter(), Cotton::Builtin::IntegerRemAdapter(), Cotton::Builtin::IntegerRshiftAdapter(), Cotton::Builtin::IntegerSubAdapter(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Cotton::Builtin::RealAddAdapter(), Cotton::Builtin::RealDivAdapter(), Cotton::Builtin::RealGeqAdapter(), Cotton::Builtin::RealGtAdapter(), Cotton::Builtin::RealLeqAdapter(), Cotton::Builtin::RealLtAdapter(), Cotton::Builtin::RealMultAdapter(), Cotton::Builtin::RealNegativeAdapter(), Cotton::Builtin::RealPositiveAdapter(), Cotton::Builtin::RealSubAdapter(), Cotton::Builtin::StringAddAdapter(), Cotton::Builtin::StringIndexAdapter(), Cotton::Builtin::stringSetMethod(), Cotton::Builtin::stringSizeMethod(), and verifyHasMethod().
verifyIsInstanceObject() [2/2]
void Cotton::Runtime::verifyIsInstanceObject (Object * obj, Type * type, const TextArea & ta)
References isInstanceObject(), ProfilerCAPTURE, signalError(), Cotton::Object::userRepr(), and Cotton::Type::userRepr().
verifyIsOfType() [1/4]
void Cotton::Runtime::verifyIsOfType (Object * obj, Runtime::BuiltinTypes type)
References ARRAY_TYPE_ID, BOOLEAN_TYPE_ID, CHARACTER_TYPE_ID, FUNCTION_TYPE_ID, INTEGER_TYPE_ID, NOTHING_TYPE_ID, ProfilerCAPTURE, REAL_TYPE_ID, signalError(), STRING_TYPE_ID, Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsValidObject().
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::ArrayType::copy(), Cotton::Builtin::BooleanType::copy(), Cotton::Builtin::CharacterType::copy(), Cotton::Builtin::FunctionType::copy(), Cotton::Builtin::IntegerType::copy(), Cotton::Builtin::NothingType::copy(), Cotton::Builtin::RealType::copy(), Cotton::Builtin::StringType::copy(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::RealEqAdapter(), and Cotton::Builtin::StringEqAdapter().
verifyIsOfType() [2/4]
void Cotton::Runtime::verifyIsOfType (Object * obj, Runtime::BuiltinTypes type, const TextArea & ta)
References ARRAY_TYPE_ID, BOOLEAN_TYPE_ID, CHARACTER_TYPE_ID, FUNCTION_TYPE_ID, INTEGER_TYPE_ID, NOTHING_TYPE_ID, ProfilerCAPTURE, REAL_TYPE_ID, signalError(), STRING_TYPE_ID, Cotton::Object::type, Cotton::Object::userRepr(), and verifyIsValidObject().
verifyIsOfType() [3/4]
void Cotton::Runtime::verifyIsOfType (Object * obj, Type * type)
References isOfType(), ProfilerCAPTURE, signalError(), Cotton::Object::userRepr(), and Cotton::Type::userRepr().
verifyIsOfType() [4/4]
void Cotton::Runtime::verifyIsOfType (Object * obj, Type * type, const TextArea & ta)
References isOfType(), ProfilerCAPTURE, signalError(), Cotton::Object::userRepr(), and Cotton::Type::userRepr().
verifyIsTypeObject() [1/2]
void Cotton::Runtime::verifyIsTypeObject (Object * obj, Type * type)
References isTypeObject(), ProfilerCAPTURE, signalError(), Cotton::Object::userRepr(), and Cotton::Type::userRepr().
Referenced by Cotton::Builtin::CF_isinsobj(), Cotton::Builtin::CF_istypeobj(), Cotton::Builtin::CF_make(), and Cotton::Builtin::CF_read().
verifyIsTypeObject() [2/2]
void Cotton::Runtime::verifyIsTypeObject (Object * obj, Type * type, const TextArea & ta)
References isTypeObject(), ProfilerCAPTURE, signalError(), Cotton::Object::userRepr(), and Cotton::Type::userRepr().
verifyIsValidObject() [1/2]
void Cotton::Runtime::verifyIsValidObject (Object * obj)
References isValidObject(), ProfilerCAPTURE, signalError(), and Cotton::Object::userRepr().
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::CF_bool(), Cotton::Builtin::CF_char(), Cotton::Builtin::CF_copy(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_int(), Cotton::Builtin::CF_isinsobj(), Cotton::Builtin::CF_istypeobj(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_real(), Cotton::Builtin::CF_repr(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_smartrun(), Cotton::Builtin::CF_string(), Cotton::Builtin::CF_typeof(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::RecordType::copy(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Type::getMethod(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::RealEqAdapter(), runOperator(), Cotton::Builtin::StringEqAdapter(), verifyHasMethod(), and verifyIsOfType().
verifyIsValidObject() [2/2]
void Cotton::Runtime::verifyIsValidObject (Object * obj, const TextArea & ta)
References isValidObject(), ProfilerCAPTURE, signalError(), and Cotton::Object::userRepr().
verifyMinArgsAmountFunc() [1/2]
void Cotton::Runtime::verifyMinArgsAmountFunc (const std::vector< Object * > & args, int64_t amount)
References ProfilerCAPTURE, and signalError().
Referenced by Cotton::Builtin::CF_assert(), Cotton::Builtin::CF_isinsobj(), and Cotton::Builtin::CF_istypeobj().
verifyMinArgsAmountFunc() [2/2]
void Cotton::Runtime::verifyMinArgsAmountFunc (const std::vector< Object * > & args, int64_t amount, const TextArea & ta)
References ProfilerCAPTURE, and signalError().
verifyMinArgsAmountMethod() [1/2]
void Cotton::Runtime::verifyMinArgsAmountMethod (const std::vector< Object * > & args, int64_t amount)
References getContext(), ProfilerCAPTURE, signalError(), and Cotton::Runtime::ErrorContext::sub_areas.
verifyMinArgsAmountMethod() [2/2]
void Cotton::Runtime::verifyMinArgsAmountMethod (const std::vector< Object * > & args, int64_t amount, const TextArea & ta)
References ProfilerCAPTURE, and signalError().
Member Data Documentation
array_type
Builtin::ArrayType* Cotton::Runtime::array_type
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::arrayResizeMethod(), Cotton::Builtin::arraySizeMethod(), Cotton::Builtin::ArrayType::copy(), Cotton::Builtin::getArrayData(), isOfType(), Cotton::Builtin::makeArrayInstanceObject(), Cotton::Builtin::mm__repr__(), and Runtime().
boolean_type
Builtin::BooleanType* Cotton::Runtime::boolean_type
Referenced by Cotton::Builtin::BooleanAndAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::BooleanNotAdapter(), Cotton::Builtin::BooleanOrAdapter(), Cotton::Builtin::CF_assert(), Cotton::Builtin::BooleanType::copy(), Cotton::Builtin::getBooleanValue(), isOfType(), Cotton::Builtin::makeBooleanInstanceObject(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), and Runtime().
character_type
Builtin::CharacterType* Cotton::Runtime::character_type
Referenced by Cotton::Builtin::CharacterAddAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::CharacterGeqAdapter(), Cotton::Builtin::CharacterGtAdapter(), Cotton::Builtin::CharacterLeqAdapter(), Cotton::Builtin::CharacterLtAdapter(), Cotton::Builtin::CharacterNegativeAdapter(), Cotton::Builtin::CharacterPositiveAdapter(), Cotton::Builtin::CharacterPostdecAdapter(), Cotton::Builtin::CharacterPostincAdapter(), Cotton::Builtin::CharacterPredecAdapter(), Cotton::Builtin::CharacterPreincAdapter(), Cotton::Builtin::CharacterSubAdapter(), Cotton::Builtin::CharacterType::copy(), Cotton::Builtin::getCharacterValue(), isOfType(), Cotton::Builtin::makeCharacterInstanceObject(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Runtime(), and Cotton::Builtin::stringSetMethod().
error_contexts
std::vector<ErrorContext> Cotton::Runtime::error_contexts
Referenced by getContext(), newContext(), popContext(), and signalError().
error_manager
ErrorManager* Cotton::Runtime::error_manager
Referenced by Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_smartrun(), Runtime(), and signalError().
exec_res_default
Object* Cotton::Runtime::exec_res_default
execution_flags
uint8_t Cotton::Runtime::execution_flags
function_type
Builtin::FunctionType* Cotton::Runtime::function_type
Referenced by Cotton::Builtin::FunctionType::copy(), Cotton::Builtin::FunctionCallAdapter(), Cotton::Builtin::FunctionEqAdapter(), isOfType(), Cotton::Builtin::makeFunctionInstanceObject(), Cotton::Builtin::mm__repr__(), and Runtime().
gc
GC* Cotton::Runtime::gc
Referenced by Cotton::GCDefaultStrategy::acknowledgeEndOfCycle(), Cotton::GCDefaultStrategy::checkConditions(), disable(), enable(), execute(), forceping(), Cotton::getList(), Cotton::Instance::Instance(), main(), Cotton::mark(), Cotton::Object::Object(), ping(), Runtime(), status(), and Cotton::Type::Type().
globals
__gnu_pbds::cc_hash_table<int64_t, Object *> Cotton::Runtime::globals
Referenced by checkGlobal(), getGlobal(), removeGlobal(), Cotton::GC::runCycle(), and setGlobal().
integer_type
Builtin::IntegerType* Cotton::Runtime::integer_type
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::ArrayIndexAdapter(), Cotton::Builtin::arrayResizeMethod(), Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_exit(), Cotton::Builtin::IntegerType::copy(), Cotton::Builtin::getIntegerValue(), Cotton::Builtin::IntegerAddAdapter(), Cotton::Builtin::IntegerBitandAdapter(), Cotton::Builtin::IntegerBitorAdapter(), Cotton::Builtin::IntegerBitxorAdapter(), Cotton::Builtin::IntegerDivAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::IntegerGeqAdapter(), Cotton::Builtin::IntegerGtAdapter(), Cotton::Builtin::IntegerInverseAdapter(), Cotton::Builtin::IntegerLeqAdapter(), Cotton::Builtin::IntegerLshiftAdapter(), Cotton::Builtin::IntegerLtAdapter(), Cotton::Builtin::IntegerMultAdapter(), Cotton::Builtin::IntegerNegativeAdapter(), Cotton::Builtin::IntegerPositiveAdapter(), Cotton::Builtin::IntegerPostdecAdapter(), Cotton::Builtin::IntegerPostincAdapter(), Cotton::Builtin::IntegerPredecAdapter(), Cotton::Builtin::IntegerPreincAdapter(), Cotton::Builtin::IntegerRemAdapter(), Cotton::Builtin::IntegerRshiftAdapter(), Cotton::Builtin::IntegerSubAdapter(), isOfType(), Cotton::Builtin::makeIntegerInstanceObject(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Runtime(), Cotton::Builtin::StringEqAdapter(), Cotton::Builtin::StringIndexAdapter(), and Cotton::Builtin::stringSetMethod().
nds
NameIds* Cotton::Runtime::nds
Referenced by Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_smartrun(), execute(), getGlobal(), Cotton::Type::getMethod(), Cotton::Scope::getVariable(), Cotton::Builtin::installArrayMethods(), Cotton::Builtin::installBuiltinFunctions(), Cotton::Builtin::installStringMethods(), library_load_point(), Cotton::MagicMethods::mm__bool__(), Cotton::MagicMethods::mm__char__(), Cotton::MagicMethods::mm__copy__(), Cotton::MagicMethods::mm__int__(), Cotton::MagicMethods::mm__make__(), Cotton::MagicMethods::mm__read__(), Cotton::MagicMethods::mm__real__(), Cotton::MagicMethods::mm__repr__(), Cotton::MagicMethods::mm__string__(), Runtime(), Cotton::Instance::selectField(), Cotton::Builtin::RecordInstance::selectField(), Cotton::Builtin::RecordInstance::userRepr(), and Cotton::Builtin::RecordType::userRepr().
nothing_type
Builtin::NothingType* Cotton::Runtime::nothing_type
Referenced by Cotton::Builtin::NothingType::copy(), isOfType(), Cotton::Builtin::makeNothingInstanceObject(), Cotton::Builtin::makeRecordInstanceObject(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::NothingEqAdapter(), and Runtime().
protected_false
Object* Cotton::Runtime::protected_false
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::ArrayNeqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::BooleanNeqAdapter(), Cotton::Builtin::BooleanNotAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::CharacterNeqAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::FunctionNeqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::IntegerNeqAdapter(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::NothingNeqAdapter(), protectedBoolean(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::RealNeqAdapter(), Runtime(), Cotton::Builtin::StringEqAdapter(), and Cotton::Builtin::StringNeqAdapter().
protected_nothing
Object* Cotton::Runtime::protected_nothing
Referenced by Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_assert(), Cotton::Builtin::CF_fork(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_isinsobj(), Cotton::Builtin::CF_istypeobj(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_print(), Cotton::Builtin::CF_println(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_readln(), Cotton::Builtin::CF_readraw(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_sleep(), Cotton::Builtin::CF_smartrun(), Cotton::Builtin::CF_system(), disable(), enable(), execute(), forceping(), getTypeObject(), ping(), Runtime(), and Cotton::Builtin::stringSetMethod().
protected_true
Object* Cotton::Runtime::protected_true
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::ArrayNeqAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::BooleanNeqAdapter(), Cotton::Builtin::BooleanNotAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::CharacterNeqAdapter(), Cotton::Builtin::FunctionEqAdapter(), Cotton::Builtin::FunctionNeqAdapter(), Cotton::Builtin::IntegerEqAdapter(), Cotton::Builtin::IntegerNeqAdapter(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::NothingEqAdapter(), Cotton::Builtin::NothingNeqAdapter(), protectedBoolean(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::RealNeqAdapter(), Runtime(), Cotton::Builtin::StringEqAdapter(), and Cotton::Builtin::StringNeqAdapter().
readonly_literals
__gnu_pbds::cc_hash_table<int64_t, Object *> Cotton::Runtime::readonly_literals
Referenced by execute().
real_type
Builtin::RealType* Cotton::Runtime::real_type
Referenced by Cotton::Builtin::CF_sleep(), Cotton::Builtin::RealType::copy(), Cotton::Builtin::getRealValue(), isOfType(), Cotton::Builtin::makeRealInstanceObject(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__char__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Cotton::Builtin::RealAddAdapter(), Cotton::Builtin::RealDivAdapter(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::RealGeqAdapter(), Cotton::Builtin::RealGtAdapter(), Cotton::Builtin::RealLeqAdapter(), Cotton::Builtin::RealLtAdapter(), Cotton::Builtin::RealMultAdapter(), Cotton::Builtin::RealNegativeAdapter(), Cotton::Builtin::RealPositiveAdapter(), Cotton::Builtin::RealSubAdapter(), and Runtime().
scope
Scope* Cotton::Runtime::scope
Referenced by Cotton::Builtin::CF_argc(), Cotton::Builtin::CF_argg(), Cotton::Builtin::CF_argv(), execute(), Cotton::Builtin::FunctionCallAdapter(), Cotton::Builtin::installBuiltinFunctions(), newFrame(), popFrame(), Cotton::GC::runCycle(), and Runtime().
string_type
Builtin::StringType* Cotton::Runtime::string_type
Referenced by Cotton::Builtin::ArrayEqAdapter(), Cotton::Builtin::CF_assert(), Cotton::Builtin::CF_checkglobal(), Cotton::Builtin::CF_cotton(), Cotton::Builtin::CF_dumbrun(), Cotton::Builtin::CF_error(), Cotton::Builtin::CF_getglobal(), Cotton::Builtin::CF_hasfield(), Cotton::Builtin::CF_hasmethod(), Cotton::Builtin::CF_loadlibrary(), Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_removeglobal(), Cotton::Builtin::CF_setglobal(), Cotton::Builtin::CF_smartrun(), Cotton::Builtin::CF_system(), Cotton::Builtin::StringType::copy(), Cotton::Builtin::getStringData(), isOfType(), Cotton::Builtin::makeStringInstanceObject(), Cotton::Builtin::mm__bool__(), Cotton::Builtin::mm__int__(), Cotton::Builtin::mm__read__(), Cotton::Builtin::mm__real__(), Cotton::Builtin::mm__repr__(), Cotton::Builtin::mm__string__(), Runtime(), Cotton::Builtin::StringAddAdapter(), Cotton::Builtin::StringEqAdapter(), Cotton::Builtin::StringIndexAdapter(), Cotton::Builtin::stringSetMethod(), and Cotton::Builtin::stringSizeMethod().
type_objects
__gnu_pbds::cc_hash_table<Type *, Object *> Cotton::Runtime::type_objects
Referenced by getTypeObject(), and registerTypeObject().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/back/runtime.h
cotton_lib/src/cotton_lib/back/runtime.cpp