Cotton::ErrorManager Class Reference
#include <errors.h>
Public Member Functions
ErrorManager ()=delete
~ErrorManager ()=default
ErrorManager (void(*emergency_error_exit)())
void setErrorFilename (const std::string &filename)
void setErrorCharPos (int64_t char_pos)
void setErrorMessage (const std::string &message)
void clearError ()
void signalError (bool eee=true)
void signalError (const std::string &message, bool eee=true)
void signalError (const std::string &message, int64_t char_pos, bool eee=true)
void signalError (const std::string &message, const Token &token, bool eee=true)
void signalError (const std::vector< std::pair< Token *, std::string >> errors, bool eee=true)
void signalErrorWithContext (const std::vector< std::pair< std::string, Token * >> messages, bool eee=true)
void signalError (const std::string &message, const TextArea &ta, bool eee=true)
Public Attributes
void(* emergency_error_exit)()
std::string error_filename
int64_t error_char_pos
std::string error_message
Friends
void __assert__ (bool value, const char *assertion, const std::string &message, ErrorManager *error_manager, const char *filename, int line)
Constructor & Destructor Documentation
ErrorManager() [1/2]
Cotton::ErrorManager::ErrorManager () [delete]
 ErrorManager()
Cotton::ErrorManager::~ErrorManager () [default]
ErrorManager() [2/2]
Cotton::ErrorManager::ErrorManager (void(*)() emergency_error_exit)
References clearError(), and emergency_error_exit.
Member Function Documentation
clearError()
void Cotton::ErrorManager::clearError ()
References error_char_pos, error_filename, and error_message.
Referenced by ErrorManager().
setErrorCharPos()
void Cotton::ErrorManager::setErrorCharPos (int64_t char_pos)
References error_char_pos.
Referenced by Cotton::Lexer::faze2FormConnectedTokens(), Cotton::Parser::parse(), signalError(), and signalErrorWithContext().
setErrorFilename()
void Cotton::ErrorManager::setErrorFilename (const std::string & filename)
References error_filename.
Referenced by Cotton::Lexer::processFile(), and signalError().
setErrorMessage()
void Cotton::ErrorManager::setErrorMessage (const std::string & message)
References error_message.
Referenced by Cotton::Parser::parse().
signalError() [1/6]
void Cotton::ErrorManager::signalError (bool eee = true)
References error_char_pos, and error_message.
Referenced by Cotton::getCharacter(), Cotton::Lexer::processFile(), Cotton::Parser::signalError(), Cotton::Runtime::signalError(), signalError(), signalErrorWithContext(), Cotton::skipCharacter(), and Cotton::skipString().
signalError() [2/6]
void Cotton::ErrorManager::signalError (const std::string & message, bool eee = true)
References error_char_pos, and signalError().
signalError() [3/6]
void Cotton::ErrorManager::signalError (const std::string & message, const TextArea & ta, bool eee = true)
References emergency_error_exit, Cotton::TextArea::filename, Cotton::TextArea::first_char, Cotton::intersection(), Cotton::TextArea::last_char, printColor(), setErrorFilename(), and signalError().
signalError() [4/6]
void Cotton::ErrorManager::signalError (const std::string & message, const Token & token, bool eee = true)
References Cotton::Token::begin_pos, eassert, emergency_error_exit, Cotton::Token::end_pos, Cotton::Token::filename, printColor(), setErrorFilename(), and signalError().
signalError() [5/6]
void Cotton::ErrorManager::signalError (const std::string & message, int64_t char_pos, bool eee = true)
References emergency_error_exit, error_filename, printColor(), setErrorFilename(), and signalError().
signalError() [6/6]
void Cotton::ErrorManager::signalError (const std::vector< std::pair< Token *, std::string >> errors, bool eee = true)
References emergency_error_exit, setErrorCharPos(), and signalError().
signalErrorWithContext()
void Cotton::ErrorManager::signalErrorWithContext (const std::vector< std::pair< std::string, Token * >> messages, bool eee = true)
References emergency_error_exit, setErrorCharPos(), and signalError().
Friends And Related Function Documentation
__assert__
void __assert__ (bool value, const char * assertion, const std::string & message, ErrorManager * error_manager, const char * filename, int line) [friend]
Member Data Documentation
emergency_error_exit
void(* Cotton::ErrorManager::emergency_error_exit) ()
Referenced by ErrorManager(), signalError(), and signalErrorWithContext().
error_char_pos
int64_t Cotton::ErrorManager::error_char_pos
Referenced by clearError(), setErrorCharPos(), and signalError().
error_filename
std::string Cotton::ErrorManager::error_filename
Referenced by clearError(), setErrorFilename(), and signalError().
error_message
std::string Cotton::ErrorManager::error_message
Referenced by clearError(), setErrorMessage(), and signalError().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/errors.h
cotton_lib/src/cotton_lib/errors.cpp