Cotton::Builtin::StringType Class Reference
#include <string.h>
Public Member Functions
size_t getInstanceSize ()
StringType (Runtime *rt)
~StringType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
StringType()
Cotton::Builtin::StringType::StringType (Runtime * rt)
References Cotton::Type::add_op, Cotton::Type::eq_op, Cotton::Type::index_op, Cotton::Type::neq_op, ProfilerCAPTURE, Cotton::Builtin::StringAddAdapter(), Cotton::Builtin::StringEqAdapter(), Cotton::Builtin::StringIndexAdapter(), and Cotton::Builtin::StringNeqAdapter().
 StringType()
Cotton::Builtin::StringType::~StringType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::StringType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Instance::copy(), Cotton::Object::instance, newObject, ProfilerCAPTURE, Cotton::Runtime::string_type, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::StringType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::StringType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::StringType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/string.h
cotton_lib/src/cotton_lib/builtin/types/string.cpp