Cotton::Builtin::CharacterType Class Reference
#include <character.h>
Public Member Functions
size_t getInstanceSize ()
CharacterType (Runtime *rt)
~CharacterType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
CharacterType()
Cotton::Builtin::CharacterType::CharacterType (Runtime * rt)
References Cotton::Type::add_op, Cotton::Builtin::CharacterAddAdapter(), Cotton::Builtin::CharacterEqAdapter(), Cotton::Builtin::CharacterGeqAdapter(), Cotton::Builtin::CharacterGtAdapter(), Cotton::Builtin::CharacterLeqAdapter(), Cotton::Builtin::CharacterLtAdapter(), Cotton::Builtin::CharacterNegativeAdapter(), Cotton::Builtin::CharacterNeqAdapter(), Cotton::Builtin::CharacterPositiveAdapter(), Cotton::Builtin::CharacterPostdecAdapter(), Cotton::Builtin::CharacterPostincAdapter(), Cotton::Builtin::CharacterPredecAdapter(), Cotton::Builtin::CharacterPreincAdapter(), Cotton::Builtin::CharacterSubAdapter(), Cotton::Type::eq_op, Cotton::Type::geq_op, Cotton::Type::gt_op, Cotton::Type::leq_op, Cotton::Type::lt_op, Cotton::Type::negative_op, Cotton::Type::neq_op, Cotton::Type::positive_op, Cotton::Type::postdec_op, Cotton::Type::postinc_op, Cotton::Type::predec_op, Cotton::Type::preinc_op, ProfilerCAPTURE, and Cotton::Type::sub_op.
 CharacterType()
Cotton::Builtin::CharacterType::~CharacterType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::CharacterType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Runtime::character_type, Cotton::Instance::copy(), Cotton::Object::instance, newObject, ProfilerCAPTURE, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::CharacterType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::CharacterType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::CharacterType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/character.h
cotton_lib/src/cotton_lib/builtin/types/character.cpp