Cotton::Builtin::CharacterInstance Class Reference
#include <character.h>
Public Member Functions
CharacterInstance (Runtime *rt)
~CharacterInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Public Attributes
uint8_t value
Additional Inherited Members
Constructor & Destructor Documentation
CharacterInstance()
Cotton::Builtin::CharacterInstance::CharacterInstance (Runtime * rt)
References ProfilerCAPTURE, and value.
Referenced by copy(), and getSize().
 CharacterInstance()
Cotton::Builtin::CharacterInstance::~CharacterInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::CharacterInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, CharacterInstance(), Cotton::Runtime::getContext(), icast, ProfilerCAPTURE, Cotton::Runtime::signalError(), userRepr(), and value.
getSize()
size_t Cotton::Builtin::CharacterInstance::getSize () [virtual]
Implements Cotton::Instance.
References CharacterInstance(), and ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::CharacterInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Builtin::charToString(), ProfilerCAPTURE, and value.
Referenced by copy().
Member Data Documentation
value
uint8_t Cotton::Builtin::CharacterInstance::value
Referenced by CharacterInstance(), copy(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/character.h
cotton_lib/src/cotton_lib/builtin/types/character.cpp