Cotton::Builtin::StringInstance Class Reference
#include <string.h>
Public Member Functions
StringInstance (Runtime *rt)
~StringInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Public Attributes
std::string data
Additional Inherited Members
Constructor & Destructor Documentation
StringInstance()
Cotton::Builtin::StringInstance::StringInstance (Runtime * rt)
References data, and ProfilerCAPTURE.
Referenced by copy(), and getSize().
 StringInstance()
Cotton::Builtin::StringInstance::~StringInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::StringInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, data, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::signalError(), StringInstance(), and userRepr().
getSize()
size_t Cotton::Builtin::StringInstance::getSize () [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE, and StringInstance().
userRepr()
std::string Cotton::Builtin::StringInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References data, and ProfilerCAPTURE.
Referenced by copy().
Member Data Documentation
data
std::string Cotton::Builtin::StringInstance::data
Referenced by copy(), StringInstance(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/string.h
cotton_lib/src/cotton_lib/builtin/types/string.cpp