Cotton::Builtin::ArrayInstance Class Reference
#include <array.h>
Public Member Functions
ArrayInstance (Runtime *rt)
~ArrayInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
std::vector< Object * > getGCReachable ()
void spreadSingleUse ()
void spreadMultiUse ()
Public Attributes
std::vector< Object * > data
Additional Inherited Members
Constructor & Destructor Documentation
ArrayInstance()
Cotton::Builtin::ArrayInstance::ArrayInstance (Runtime * rt)
References data, and ProfilerCAPTURE.
Referenced by copy(), and getSize().
 ArrayInstance()
Cotton::Builtin::ArrayInstance::~ArrayInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::ArrayInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, ArrayInstance(), Cotton::Runtime::copy(), data, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::signalError(), and userRepr().
getGCReachable()
std::vector< Object * > Cotton::Builtin::ArrayInstance::getGCReachable () [virtual]
Reimplemented from Cotton::Instance.
References data, Cotton::Instance::getGCReachable(), and ProfilerCAPTURE.
getSize()
size_t Cotton::Builtin::ArrayInstance::getSize () [virtual]
Implements Cotton::Instance.
References ArrayInstance(), and ProfilerCAPTURE.
spreadMultiUse()
void Cotton::Builtin::ArrayInstance::spreadMultiUse () [virtual]
Reimplemented from Cotton::Instance.
References data, and ProfilerCAPTURE.
spreadSingleUse()
void Cotton::Builtin::ArrayInstance::spreadSingleUse () [virtual]
Reimplemented from Cotton::Instance.
References data, and ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::ArrayInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References data, and ProfilerCAPTURE.
Referenced by copy().
Member Data Documentation
data
std::vector<Object *> Cotton::Builtin::ArrayInstance::data
Referenced by ArrayInstance(), copy(), getGCReachable(), spreadMultiUse(), spreadSingleUse(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/array.h
cotton_lib/src/cotton_lib/builtin/types/array.cpp