Cotton::Builtin::IntegerInstance Class Reference
#include <integer.h>
Public Member Functions
IntegerInstance (Runtime *rt)
~IntegerInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Public Attributes
int64_t value
Additional Inherited Members
Constructor & Destructor Documentation
IntegerInstance()
Cotton::Builtin::IntegerInstance::IntegerInstance (Runtime * rt)
References ProfilerCAPTURE, and value.
Referenced by copy(), and getSize().
 IntegerInstance()
Cotton::Builtin::IntegerInstance::~IntegerInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::IntegerInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), icast, IntegerInstance(), ProfilerCAPTURE, Cotton::Runtime::signalError(), userRepr(), and value.
getSize()
size_t Cotton::Builtin::IntegerInstance::getSize () [virtual]
Implements Cotton::Instance.
References IntegerInstance(), and ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::IntegerInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE, and value.
Referenced by copy().
Member Data Documentation
value
int64_t Cotton::Builtin::IntegerInstance::value
Referenced by copy(), IntegerInstance(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/integer.h
cotton_lib/src/cotton_lib/builtin/types/integer.cpp