Cotton::Builtin::RealType Class Reference
#include <real.h>
Public Member Functions
size_t getInstanceSize ()
RealType (Runtime *rt)
~RealType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
RealType()
Cotton::Builtin::RealType::RealType (Runtime * rt)
References Cotton::Type::add_op, Cotton::Type::div_op, Cotton::Type::eq_op, Cotton::Type::geq_op, Cotton::Type::gt_op, Cotton::Type::leq_op, Cotton::Type::lt_op, Cotton::Type::mult_op, Cotton::Type::negative_op, Cotton::Type::neq_op, Cotton::Type::positive_op, ProfilerCAPTURE, Cotton::Builtin::RealAddAdapter(), Cotton::Builtin::RealDivAdapter(), Cotton::Builtin::RealEqAdapter(), Cotton::Builtin::RealGeqAdapter(), Cotton::Builtin::RealGtAdapter(), Cotton::Builtin::RealLeqAdapter(), Cotton::Builtin::RealLtAdapter(), Cotton::Builtin::RealMultAdapter(), Cotton::Builtin::RealNegativeAdapter(), Cotton::Builtin::RealNeqAdapter(), Cotton::Builtin::RealPositiveAdapter(), Cotton::Builtin::RealSubAdapter(), and Cotton::Type::sub_op.
 RealType()
Cotton::Builtin::RealType::~RealType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::RealType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Instance::copy(), Cotton::Object::instance, newObject, ProfilerCAPTURE, Cotton::Runtime::real_type, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::RealType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::RealType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::RealType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/real.h
cotton_lib/src/cotton_lib/builtin/types/real.cpp