Cotton::Builtin::RealInstance Class Reference
#include <real.h>
Public Member Functions
RealInstance (Runtime *rt)
~RealInstance ()
Instance * copy (Runtime *rt)
size_t getSize ()
std::string userRepr (Runtime *rt)
Public Attributes
double value
Additional Inherited Members
Constructor & Destructor Documentation
RealInstance()
Cotton::Builtin::RealInstance::RealInstance (Runtime * rt)
References ProfilerCAPTURE, and value.
Referenced by copy(), and getSize().
 RealInstance()
Cotton::Builtin::RealInstance::~RealInstance ()
References ProfilerCAPTURE.
Member Function Documentation
copy()
Instance * Cotton::Builtin::RealInstance::copy (Runtime * rt) [virtual]
Implements Cotton::Instance.
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), icast, ProfilerCAPTURE, RealInstance(), Cotton::Runtime::signalError(), userRepr(), and value.
getSize()
size_t Cotton::Builtin::RealInstance::getSize () [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE, and RealInstance().
userRepr()
std::string Cotton::Builtin::RealInstance::userRepr (Runtime * rt) [virtual]
Implements Cotton::Instance.
References ProfilerCAPTURE, and value.
Referenced by copy().
Member Data Documentation
value
double Cotton::Builtin::RealInstance::value
Referenced by copy(), RealInstance(), and userRepr().
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/real.h
cotton_lib/src/cotton_lib/builtin/types/real.cpp