Cotton::GCStrategy Class Reference
An abstract class representing a garbage collector strategy.
#include <gc.h>
Public Member Functions
virtual void acknowledgeTrack (Object *object)=0
Acknowledges track of an Object. This function is called by the gc.
virtual void acknowledgeTrack (Instance *instance, size_t bytes)=0
Acknowledges track of an Instance. This function is called by the gc.
virtual void acknowledgeTrack (Type *type)=0
Acknowledges track of a Type. This function is called by the gc.
virtual void acknowledgeUntrack (Object *object)=0
Acknowledges untrack of an Object. This function is called by the gc.
virtual void acknowledgeUntrack (Instance *instance)=0
Acknowledges untrack of an Instance. This function is called by the gc.
virtual void acknowledgeUntrack (Type *type)=0
Acknowledges untrack of a Type. This function is called by the gc.
virtual void acknowledgeEndOfCycle (Runtime *rt)=0
Acknowledges the end of a gc cycle. This function is called by the gc.
virtual void acknowledgePing (Runtime *rt)=0
Acknowledges a gc ping event. This function is called by the gc.
Detailed Description
An abstract class representing a garbage collector strategy.
Member Function Documentation
acknowledgeEndOfCycle()
virtual void Cotton::GCStrategy::acknowledgeEndOfCycle (Runtime * rt) [pure virtual]
Acknowledges the end of a gc cycle. This function is called by the gc.
Parameters
rt The Runtime. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
Referenced by Cotton::GC::runCycle().
acknowledgePing()
virtual void Cotton::GCStrategy::acknowledgePing (Runtime * rt) [pure virtual]
Acknowledges a gc ping event. This function is called by the gc.
Parameters
rt The Runtime. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
Referenced by Cotton::GC::ping().
acknowledgeTrack() [1/3]
virtual void Cotton::GCStrategy::acknowledgeTrack (Instance * instance, size_t bytes) [pure virtual]
Acknowledges track of an Instance. This function is called by the gc.
Parameters
instance The Instance that got tracked. Assumed to be valid.
bytes Size of the instance in bytes. It is added to the total size counter.
Implemented in Cotton::GCDefaultStrategy.
acknowledgeTrack() [2/3]
virtual void Cotton::GCStrategy::acknowledgeTrack (Object * object) [pure virtual]
Acknowledges track of an Object. This function is called by the gc.
Parameters
object The object that got tracked. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
Referenced by Cotton::GC::track().
acknowledgeTrack() [3/3]
virtual void Cotton::GCStrategy::acknowledgeTrack (Type * type) [pure virtual]
Acknowledges track of a Type. This function is called by the gc.
Parameters
type The type that got tracked. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
acknowledgeUntrack() [1/3]
virtual void Cotton::GCStrategy::acknowledgeUntrack (Instance * instance) [pure virtual]
Acknowledges untrack of an Instance. This function is called by the gc.
Parameters
instance The instance that got untracked. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
acknowledgeUntrack() [2/3]
virtual void Cotton::GCStrategy::acknowledgeUntrack (Object * object) [pure virtual]
Acknowledges untrack of an Object. This function is called by the gc.
Parameters
object The object that got untracked. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
acknowledgeUntrack() [3/3]
virtual void Cotton::GCStrategy::acknowledgeUntrack (Type * type) [pure virtual]
Acknowledges untrack of a Type. This function is called by the gc.
Parameters
type The type that got untracked. Assumed to be valid.
Implemented in Cotton::GCDefaultStrategy.
The documentation for this class was generated from the following file:
cotton_lib/src/cotton_lib/back/gc.h