Cotton::Builtin::BooleanType Class Reference
#include <boolean.h>
Public Member Functions
size_t getInstanceSize ()
BooleanType (Runtime *rt)
~BooleanType ()=default
Object * create (Runtime *rt)
Object * copy (Object *obj, Runtime *rt)
std::string userRepr (Runtime *rt)
Additional Inherited Members
Constructor & Destructor Documentation
BooleanType()
Cotton::Builtin::BooleanType::BooleanType (Runtime * rt)
References Cotton::Type::and_op, Cotton::Builtin::BooleanAndAdapter(), Cotton::Builtin::BooleanEqAdapter(), Cotton::Builtin::BooleanNeqAdapter(), Cotton::Builtin::BooleanNotAdapter(), Cotton::Builtin::BooleanOrAdapter(), Cotton::Type::eq_op, Cotton::Type::neq_op, Cotton::Type::not_op, Cotton::Type::or_op, and ProfilerCAPTURE.
 BooleanType()
Cotton::Builtin::BooleanType::~BooleanType () [default]
Member Function Documentation
copy()
Object * Cotton::Builtin::BooleanType::copy (Object * obj, Runtime * rt) [virtual]
Implements Cotton::Type.
References Cotton::Runtime::boolean_type, Cotton::Instance::copy(), Cotton::Object::instance, newObject, ProfilerCAPTURE, and Cotton::Runtime::verifyIsOfType().
create()
Object * Cotton::Builtin::BooleanType::create (Runtime * rt) [virtual]
Implements Cotton::Type.
References newObject, and ProfilerCAPTURE.
getInstanceSize()
size_t Cotton::Builtin::BooleanType::getInstanceSize () [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
userRepr()
std::string Cotton::Builtin::BooleanType::userRepr (Runtime * rt) [virtual]
Implements Cotton::Type.
References ProfilerCAPTURE.
The documentation for this class was generated from the following files:
cotton_lib/src/cotton_lib/builtin/types/boolean.h
cotton_lib/src/cotton_lib/builtin/types/boolean.cpp