cotton_modules/gc.cpp File Reference
#include `../cotton_lib/src/cotton_lib/api.h`
Functions
static Object * enable (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * disable (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * status (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * ping (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * forceping (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
Object * library_load_point (Runtime *rt)
Function Documentation
disable()
static Object* disable (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::GC::disable(), Cotton::Runtime::gc, Cotton::Runtime::protected_nothing, and Cotton::Runtime::verifyExactArgsAmountMethod().
Referenced by library_load_point().
enable()
static Object* enable (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::GC::enable(), Cotton::Runtime::gc, Cotton::Runtime::protected_nothing, and Cotton::Runtime::verifyExactArgsAmountMethod().
Referenced by library_load_point().
forceping()
static Object* forceping (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::GC::enable(), Cotton::GC::enabled, Cotton::Runtime::gc, Cotton::GC::ping(), Cotton::Runtime::protected_nothing, status(), and Cotton::Runtime::verifyExactArgsAmountMethod().
Referenced by library_load_point().
library_load_point()
Object* library_load_point (Runtime * rt)
References disable(), enable(), forceping(), Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), Cotton::Builtin::makeFunctionInstanceObject(), Cotton::Builtin::makeRecordType(), Cotton::Runtime::nds, ping(), and status().
ping()
static Object* ping (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::gc, Cotton::GC::ping(), Cotton::Runtime::protected_nothing, and Cotton::Runtime::verifyExactArgsAmountMethod().
Referenced by library_load_point().
status()
static Object* status (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::GC::enabled, Cotton::Runtime::gc, Cotton::Runtime::protectedBoolean(), and Cotton::Runtime::verifyExactArgsAmountMethod().
Referenced by forceping(), and library_load_point().