cotton_int/src/cotton.cpp File Reference
#include <chrono>
#include <cotton_lib/api.h>
#include <cstring>
Functions
void emergency_error_exit ()
int main (int argc, char *argv[])
Function Documentation
emergency_error_exit()
void emergency_error_exit ()
Referenced by main().
main()
int main (int argc, char * argv[])
References Cotton::GC::disable(), emergency_error_exit(), Cotton::Runtime::execute(), Cotton::Runtime::gc, Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::isValidObject(), Cotton::Parser::parse(), Cotton::Profiler::printResult(), and Cotton::Lexer::processFile().