Cotton Namespace Reference
Namespaces
 Builtin
 MagicMethods
 Profiler
Classes
class GCStrategy
An abstract class representing a garbage collector strategy.
class GCDefaultStrategy
The default gc strategy.
class GC
Garbage collector class.
class Instance
Class representing an instance of a type.
class NameId
class NameIds
class Object
class Runtime
class Scope
class Type
class ErrorManager
class Token
class Lexer
class TextArea
class ExprNode
class FuncDefNode
class TypeDefNode
class OperatorNode
class AtomNode
class ParExprNode
class IdentListNode
class StmtNode
class WhileStmtNode
class ForStmtNode
class IfStmtNode
class ReturnStmtNode
class BlockStmtNode
class Parser
Typedefs
typedef Object *(* LibraryLoadPoint) (Runtime *rt)
typedef Object *(* UnaryOperatorAdapter) (Object *self, Runtime *rt, bool execution_result_matters)
typedef Object *(* BinaryOperatorAdapter) (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
typedef Object *(* NaryOperatorAdapter) (Object *self, const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
Functions
static void mark (Instance *ins, Runtime *rt)
static void mark (Type *type, Runtime *rt)
static void mark (Object *obj, Runtime *rt)
std::ostream & operator<< (std::ostream &stream, Object *obj)
static std::vector< Object * > getList (ExprNode *expr, Runtime *rt)
static void getList_addToContext (ExprNode *expr, Runtime *rt)
static bool intersection (int64_t l, int64_t r, int64_t L, int64_t R)
void __assert__ (bool value, const char *assertion, const std::string &message, ErrorManager *error_manager, const char *filename, int line)
static char getCharacter (std::string::const_iterator &it, const std::string &str, ErrorManager *error_manager)
static std::string parseString (const std::string &str, ErrorManager *error_manager)
std::ostream & operator<< (std::ostream &out, const Token &token)
static void skipString (Lexer &lexer, std::string::iterator &it, std::string &str)
static void skipCharacter (Lexer &lexer, std::string::iterator &it, std::string &str)
static void splitByOperator (const Token &token, std::string::const_iterator &split_end, std::string::const_iterator &it, std::vector< Token > &res, const std::string &splitter)
static void printPrefix (int indent, int step, bool init=true)
void __passert__ (bool value, const char *assertion, const std::string &message, Parser *parser, const char *filename, int line)
static bool skipSemicolons (Parser *parser, bool single=false)
Variables
static std::vector< std::string > sortedSplitters
Typedef Documentation
BinaryOperatorAdapter
typedef Object*(* Cotton::BinaryOperatorAdapter) (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
LibraryLoadPoint
typedef Object*(* Cotton::LibraryLoadPoint) (Runtime *rt)
NaryOperatorAdapter
typedef Object*(* Cotton::NaryOperatorAdapter) (Object *self, const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
UnaryOperatorAdapter
typedef Object*(* Cotton::UnaryOperatorAdapter) (Object *self, Runtime *rt, bool execution_result_matters)
Function Documentation
__assert__()
void Cotton::__assert__ (bool value, const char * assertion, const std::string & message, ErrorManager * error_manager, const char * filename, int line)
__passert__()
void Cotton::__passert__ (bool value, const char * assertion, const std::string & message, Parser * parser, const char * filename, int line)
References Cotton::Parser::signalError().
getCharacter()
static char Cotton::getCharacter (std::string::const_iterator & it, const std::string & str, ErrorManager * error_manager) [static]
References Cotton::ErrorManager::signalError().
Referenced by Cotton::Lexer::faze2FormConnectedTokens(), and parseString().
getList()
static std::vector<Object *> Cotton::getList (ExprNode * expr, Runtime * rt) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::OperatorNode::COMMA, Cotton::Runtime::copy(), Cotton::Runtime::execute(), Cotton::OperatorNode::first, Cotton::Runtime::gc, Cotton::Runtime::getContext(), Cotton::GC::hold(), Cotton::ExprNode::id, Cotton::OperatorNode::id, isExecFlagDIRECT_PASS, Cotton::Runtime::newContext(), Cotton::ExprNode::op, Cotton::ExprNode::OPERATOR, Cotton::Runtime::popContext(), ProfilerCAPTURE, Cotton::OperatorNode::second, and Cotton::ExprNode::text_area.
Referenced by Cotton::Runtime::execute().
getList_addToContext()
static void Cotton::getList_addToContext (ExprNode * expr, Runtime * rt) [static]
References Cotton::OperatorNode::COMMA, Cotton::OperatorNode::first, Cotton::Runtime::getContext(), Cotton::ExprNode::id, Cotton::OperatorNode::id, Cotton::ExprNode::op, Cotton::ExprNode::OPERATOR, ProfilerCAPTURE, Cotton::OperatorNode::second, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::ExprNode::text_area.
Referenced by Cotton::Runtime::execute().
intersection()
static bool Cotton::intersection (int64_t l, int64_t r, int64_t L, int64_t R) [static]
Referenced by Cotton::ErrorManager::signalError().
mark() [1/3]
static void Cotton::mark (Instance * ins, Runtime * rt) [static]
References Cotton::Runtime::gc, Cotton::GC::gc_mark, Cotton::Instance::gc_mark, Cotton::Instance::getGCReachable(), and ProfilerCAPTURE.
Referenced by mark(), and Cotton::GC::runCycle().
mark() [2/3]
static void Cotton::mark (Object * obj, Runtime * rt) [static]
References Cotton::Runtime::gc, Cotton::GC::gc_mark, Cotton::Object::gc_mark, Cotton::Object::getGCReachable(), Cotton::Object::instance, mark(), ProfilerCAPTURE, and Cotton::Object::type.
mark() [3/3]
static void Cotton::mark (Type * type, Runtime * rt) [static]
References Cotton::Runtime::gc, Cotton::GC::gc_mark, Cotton::Type::gc_mark, Cotton::Type::getGCReachable(), mark(), and ProfilerCAPTURE.
operator<<() [1/2]
std::ostream & Cotton::operator<< (std::ostream & out, const Token & token)
References Cotton::Token::AND_OP, Cotton::Token::ASSIGN_DIV_OP, Cotton::Token::ASSIGN_MINUS_OP, Cotton::Token::ASSIGN_MULT_OP, Cotton::Token::ASSIGN_OP, Cotton::Token::ASSIGN_PLUS_OP, Cotton::Token::ASSIGN_REMAINDER_OP, Cotton::Token::AT_OP, Cotton::Token::BITAND_OP, Cotton::Token::BITOR_OP, Cotton::Token::BITXOR_OP, Cotton::Token::bool_value, Cotton::Token::BOOLEAN_LIT, Cotton::Token::BREAK_KW, Cotton::Token::CHAR_LIT, Cotton::Token::char_value, Cotton::Token::CLOSE_BRACKET, Cotton::Token::CLOSE_CURLY_BRACKET, Cotton::Token::CLOSE_SQUARE_BRACKET, Cotton::Token::COMMA, Cotton::Token::CONTINUE_KW, Cotton::Token::data, Cotton::Token::DIV_OP, Cotton::Token::DOT_OP, Cotton::Token::ELSE_KW, Cotton::Token::EQUAL_OP, Cotton::Token::FOR_KW, Cotton::Token::FUNCTION_KW, Cotton::Token::GREATER_EQUAL_OP, Cotton::Token::GREATER_OP, Cotton::Token::id, Cotton::Token::IDENTIFIER, Cotton::Token::IF_KW, Cotton::Token::INT_LIT, Cotton::Token::int_value, Cotton::Token::INVERSE_OP, Cotton::Token::LEFT_SHIFT_OP, Cotton::Token::LESS_EQUAL_OP, Cotton::Token::LESS_OP, Cotton::Token::METHOD_KW, Cotton::Token::MINUS_MINUS_OP, Cotton::Token::MINUS_OP, Cotton::Token::MULT_OP, Cotton::Token::NOT_EQUAL_OP, Cotton::Token::NOT_OP, Cotton::Token::NOTHING_LIT, Cotton::Token::OPEN_BRACKET, Cotton::Token::OPEN_CURLY_BRACKET, Cotton::Token::OPEN_SQUARE_BRACKET, Cotton::Token::OR_OP, Cotton::Token::PLUS_OP, Cotton::Token::PLUS_PLUS_OP, Cotton::Token::REAL_LIT, Cotton::Token::real_value, Cotton::Token::REMAINDER_OP, Cotton::Token::RETURN_KW, Cotton::Token::RIGHT_SHIFT_OP, Cotton::Token::SEMICOLON, Cotton::Token::STRING_LIT, Cotton::Token::string_value, Cotton::Token::TYPE_KW, Cotton::Token::UNSCOPED_KW, and Cotton::Token::WHILE_KW.
operator<<() [2/2]
std::ostream & Cotton::operator<< (std::ostream & stream, Object * obj)
References Cotton::Object::gc_mark, Cotton::Object::instance, Cotton::Object::is_instance, ProfilerCAPTURE, and Cotton::Object::type.
parseString()
static std::string Cotton::parseString (const std::string & str, ErrorManager * error_manager) [static]
References eassert, and getCharacter().
Referenced by Cotton::Token::identify().
printPrefix()
static void Cotton::printPrefix (int indent, int step, bool init = true) [static]
Referenced by Cotton::ExprNode::print(), Cotton::FuncDefNode::print(), Cotton::TypeDefNode::print(), Cotton::OperatorNode::print(), Cotton::AtomNode::print(), Cotton::ParExprNode::print(), Cotton::IdentListNode::print(), Cotton::StmtNode::print(), Cotton::WhileStmtNode::print(), Cotton::ForStmtNode::print(), Cotton::IfStmtNode::print(), Cotton::ReturnStmtNode::print(), and Cotton::BlockStmtNode::print().
skipCharacter()
static void Cotton::skipCharacter (Lexer & lexer, std::string::iterator & it, std::string & str) [static]
References Cotton::Lexer::error_manager, and Cotton::ErrorManager::signalError().
Referenced by Cotton::Lexer::faze1FillComments().
skipSemicolons()
static bool Cotton::skipSemicolons (Parser * parser, bool single = false) [static]
References Cotton::Parser::consume(), Cotton::Parser::hasNext(), and Cotton::Token::SEMICOLON.
Referenced by Cotton::Parser::parse(), and Cotton::Parser::parseStmt().
skipString()
static void Cotton::skipString (Lexer & lexer, std::string::iterator & it, std::string & str) [static]
References Cotton::Lexer::error_manager, and Cotton::ErrorManager::signalError().
Referenced by Cotton::Lexer::faze1FillComments().
splitByOperator()
static void Cotton::splitByOperator (const Token & token, std::string::const_iterator & split_end, std::string::const_iterator & it, std::vector< Token > & res, const std::string & splitter) [static]
References Cotton::Token::begin_pos, and Cotton::Token::data.
Referenced by Cotton::Lexer::faze3SplitByOperatorsAndSeparators(), and Cotton::Lexer::faze4FindRealNumbers().
Variable Documentation
sortedSplitters
std::vector<std::string> Cotton::sortedSplitters [static]
Initial value:
= {"(", ")", "{", "}", "@", ";", "++", "--", "[", "]", "+=", "-=", "!=", "~", "*=", "/=", "%=", ">>",
   "<<", "<=", "<", ">=", ">", "==", "!", "&", "^", "|", "=", "+", "-", "*", "/", "%", ","}
Referenced by Cotton::Lexer::faze3SplitByOperatorsAndSeparators().