Cotton::Builtin Namespace Reference
Classes
class ArrayInstance
class ArrayType
class BooleanInstance
class BooleanType
class CharacterInstance
class CharacterType
class FunctionInstance
class FunctionType
class IntegerInstance
class IntegerType
class NothingInstance
class NothingType
class RealInstance
class RealType
class RecordInstance
class RecordType
class StringInstance
class StringType
Typedefs
typedef Object *(* InternalFunction) (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
Functions
static Object * CF_make (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_copy (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_bool (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_char (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_int (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_real (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_string (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_printraw (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_print (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_printf (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_println (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_readraw (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_read (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_readln (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_exit (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_fork (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_system (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_sleep (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_error (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_cotton (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_argc (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_argv (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_argg (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_typeof (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_isinsobj (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_istypeobj (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_repr (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_hasfield (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_hasmethod (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_assert (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_checkglobal (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_getglobal (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_setglobal (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_removeglobal (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_smartrun (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_dumbrun (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * CF_loadlibrary (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installBuiltinFunctions (Runtime *rt)
static Object * ArrayIndexAdapter (Object *self, const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * ArrayEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * ArrayNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * arraySizeMethod (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * arrayResizeMethod (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installArrayMethods (Type *type, Runtime *rt)
std::vector< Object * > & getArrayData (Object *obj, Runtime *rt)
std::vector< Object * > & getArrayData (Object *obj, Runtime *rt, const TextArea &ta)
Object * makeArrayInstanceObject (const std::vector< Object * > &data, Runtime *rt)
static Object * BooleanNotAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * BooleanEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * BooleanNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * BooleanAndAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * BooleanOrAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * mm__bool__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__char__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__int__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__real__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__string__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__read__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installBooleanMethods (Type *type, Runtime *rt)
bool & getBooleanValue (Object *obj, Runtime *rt)
bool & getBooleanValue (Object *obj, Runtime *rt, const TextArea &ta)
Object * makeBooleanInstanceObject (bool value, Runtime *rt)
static std::string charToString (char c)
static Object * CharacterPostincAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * CharacterPostdecAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * CharacterPreincAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * CharacterPredecAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * CharacterPositiveAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * CharacterNegativeAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * CharacterAddAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterSubAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterLtAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterLeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterGtAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterGeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * CharacterNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * mm__bool__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__char__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__int__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__real__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__string__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__read__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installCharacterMethods (Type *type, Runtime *rt)
uint8_t & getCharacterValue (Object *obj, Runtime *rt)
uint8_t & getCharacterValue (Object *obj, Runtime *rt, const TextArea &ta)
Object * makeCharacterInstanceObject (uint8_t value, Runtime *rt)
static Object * FunctionCallAdapter (Object *self, const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * FunctionEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * FunctionNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installFunctionMethods (Type *type, Runtime *rt)
Object * makeFunctionInstanceObject (bool is_internal, InternalFunction internal_ptr, FuncDefNode *cotton_ptr, Runtime *rt)
static Object * IntegerPostincAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerPostdecAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerPreincAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerPredecAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerPositiveAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerNegativeAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerInverseAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * IntegerMultAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerDivAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerRemAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerRshiftAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerLshiftAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerAddAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerSubAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerLtAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerLeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerGtAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerGeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerBitandAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerBitxorAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * IntegerBitorAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * mm__bool__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__char__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__int__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__real__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__string__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__read__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installIntegerMethods (Type *type, Runtime *rt)
int64_t & getIntegerValue (Object *obj, Runtime *rt)
int64_t & getIntegerValue (Object *obj, Runtime *rt, const TextArea &ta)
Object * makeIntegerInstanceObject (int64_t value, Runtime *rt)
static Object * NothingEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * NothingNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installNothingMethods (Type *type, Runtime *rt)
Object * makeNothingInstanceObject (Runtime *rt)
static Object * RealPositiveAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * RealNegativeAdapter (Object *self, Runtime *rt, bool execution_result_matters)
static Object * RealMultAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealDivAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealAddAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealSubAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealLtAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealLeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealGtAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealGeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * RealNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * mm__bool__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__char__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__int__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__real__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__string__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__read__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installRealMethods (Type *type, Runtime *rt)
double & getRealValue (Object *obj, Runtime *rt)
double & getRealValue (Object *obj, Runtime *rt, const TextArea &ta)
Object * makeRealInstanceObject (double value, Runtime *rt)
Object * makeRecordInstanceObject (Runtime *rt)
RecordType * makeRecordType (int64_t nameid, Runtime *rt)
static Object * StringIndexAdapter (Object *self, const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * StringAddAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * StringEqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * StringNeqAdapter (Object *self, Object *arg, Runtime *rt, bool execution_result_matters)
static Object * stringSizeMethod (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * stringSetMethod (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__bool__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__int__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__real__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__string__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__repr__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
static Object * mm__read__ (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
void installStringMethods (Type *type, Runtime *rt)
std::string & getStringData (Object *obj, Runtime *rt)
std::string & getStringData (Object *obj, Runtime *rt, const TextArea &ta)
Object * makeStringInstanceObject (const std::string &value, Runtime *rt)
Typedef Documentation
InternalFunction
typedef Object*(* Cotton::Builtin::InternalFunction) (const std::vector< Object * > &args, Runtime *rt, bool execution_result_matters)
Function Documentation
ArrayEqAdapter()
static Object* Cotton::Builtin::ArrayEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::array_type, Cotton::OperatorNode::EQUAL, getArrayDataFast, getBooleanValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::integer_type, Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), Cotton::Runtime::newContext(), Cotton::Runtime::popContext(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::runOperator(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by ArrayNeqAdapter(), and Cotton::Builtin::ArrayType::ArrayType().
ArrayIndexAdapter()
static Object* Cotton::Builtin::ArrayIndexAdapter (Object * self, const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::array_type, getArrayDataFast, Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::signalError(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::ArrayType::ArrayType().
ArrayNeqAdapter()
static Object* Cotton::Builtin::ArrayNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References ArrayEqAdapter(), getBooleanValueFast, ProfilerCAPTURE, Cotton::Runtime::protected_false, and Cotton::Runtime::protected_true.
Referenced by Cotton::Builtin::ArrayType::ArrayType().
arrayResizeMethod()
static Object* Cotton::Builtin::arrayResizeMethod (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::array_type, getArrayDataFast, Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeNothingInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::signalError(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installArrayMethods().
arraySizeMethod()
static Object* Cotton::Builtin::arraySizeMethod (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::array_type, getArrayDataFast, Cotton::Runtime::getContext(), makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installArrayMethods().
BooleanAndAdapter()
static Object* Cotton::Builtin::BooleanAndAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::BooleanType::BooleanType().
BooleanEqAdapter()
static Object* Cotton::Builtin::BooleanEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by BooleanNeqAdapter(), and Cotton::Builtin::BooleanType::BooleanType().
BooleanNeqAdapter()
static Object* Cotton::Builtin::BooleanNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References BooleanEqAdapter(), getBooleanValue(), ProfilerCAPTURE, Cotton::Runtime::protected_false, and Cotton::Runtime::protected_true.
Referenced by Cotton::Builtin::BooleanType::BooleanType().
BooleanNotAdapter()
static Object* Cotton::Builtin::BooleanNotAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::BooleanType::BooleanType().
BooleanOrAdapter()
static Object* Cotton::Builtin::BooleanOrAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::BooleanType::BooleanType().
CF_argc()
static Object* Cotton::Builtin::CF_argc (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References makeIntegerInstanceObject(), Cotton::Scope::prev, ProfilerCAPTURE, Cotton::Runtime::scope, and Cotton::Runtime::verifyExactArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_argg()
static Object* Cotton::Builtin::CF_argg (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValue(), Cotton::Runtime::integer_type, Cotton::Scope::prev, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::scope, Cotton::Runtime::signalError(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_argv()
static Object* Cotton::Builtin::CF_argv (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References makeArrayInstanceObject(), Cotton::Scope::prev, ProfilerCAPTURE, Cotton::Runtime::scope, and Cotton::Runtime::verifyExactArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_assert()
static Object* Cotton::Builtin::CF_assert (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), getStringDataFast, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyMinArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_bool()
static Object* Cotton::Builtin::CF_bool (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__bool__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_char()
static Object* Cotton::Builtin::CF_char (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__char__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_checkglobal()
static Object* Cotton::Builtin::CF_checkglobal (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::checkGlobal(), Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_copy()
static Object* Cotton::Builtin::CF_copy (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::copy(), Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__copy__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_cotton()
static Object* Cotton::Builtin::CF_cotton (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::error_manager, Cotton::Runtime::execute(), Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::NameId::id, Cotton::Runtime::nds, Cotton::Parser::parse(), Cotton::Lexer::process(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_dumbrun()
static Object* Cotton::Builtin::CF_dumbrun (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::error_manager, Cotton::Runtime::execute(), Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::NameId::id, Cotton::Runtime::nds, Cotton::Runtime::newFrame(), Cotton::Parser::parse(), Cotton::Runtime::popFrame(), Cotton::Lexer::processFile(), ProfilerCAPTURE, Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_error()
static Object* Cotton::Builtin::CF_error (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), getStringDataFast, ProfilerCAPTURE, Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_exit()
static Object* Cotton::Builtin::CF_exit (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_fork()
static Object* Cotton::Builtin::CF_fork (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, and Cotton::Runtime::verifyExactArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_getglobal()
static Object* Cotton::Builtin::CF_getglobal (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::NameIds::get(), Cotton::Runtime::getContext(), Cotton::Runtime::getGlobal(), getStringDataFast, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_hasfield()
static Object* Cotton::Builtin::CF_hasfield (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_hasmethod()
static Object* Cotton::Builtin::CF_hasmethod (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_int()
static Object* Cotton::Builtin::CF_int (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__int__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_isinsobj()
static Object* Cotton::Builtin::CF_isinsobj (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::isInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsTypeObject(), Cotton::Runtime::verifyIsValidObject(), and Cotton::Runtime::verifyMinArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_istypeobj()
static Object* Cotton::Builtin::CF_istypeobj (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::isInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsTypeObject(), Cotton::Runtime::verifyIsValidObject(), and Cotton::Runtime::verifyMinArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_loadlibrary()
static Object* Cotton::Builtin::CF_loadlibrary (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::checkGlobal(), Cotton::NameIds::get(), Cotton::Runtime::getContext(), Cotton::Runtime::getGlobal(), getStringDataFast, Cotton::NameId::id, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::setGlobal(), Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_make()
static Object* Cotton::Builtin::CF_make (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::isValidObject(), Cotton::Runtime::make(), Cotton::MagicMethods::mm__make__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsTypeObject().
Referenced by installBuiltinFunctions().
CF_print()
static Object* Cotton::Builtin::CF_print (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, CF_printraw(), Cotton::Runtime::getContext(), Cotton::Runtime::newContext(), Cotton::Runtime::popContext(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, and Cotton::Runtime::ErrorContext::sub_areas.
Referenced by CF_println(), and installBuiltinFunctions().
CF_printf()
static Object* Cotton::Builtin::CF_printf (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References ProfilerCAPTURE.
Referenced by installBuiltinFunctions().
CF_println()
static Object* Cotton::Builtin::CF_println (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References CF_print(), ProfilerCAPTURE, and Cotton::Runtime::protected_nothing.
Referenced by installBuiltinFunctions().
CF_printraw()
static Object* Cotton::Builtin::CF_printraw (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::isInstanceObject(), Cotton::MagicMethods::mm__repr__(), Cotton::Runtime::newContext(), Cotton::Runtime::popContext(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::runMethod(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by CF_print(), and installBuiltinFunctions().
CF_read()
static Object* Cotton::Builtin::CF_read (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__read__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsTypeObject().
Referenced by installBuiltinFunctions().
CF_readln()
static Object* Cotton::Builtin::CF_readln (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, and Cotton::Runtime::verifyExactArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_readraw()
static Object* Cotton::Builtin::CF_readraw (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, and Cotton::Runtime::verifyExactArgsAmountFunc().
Referenced by installBuiltinFunctions().
CF_real()
static Object* Cotton::Builtin::CF_real (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__real__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_removeglobal()
static Object* Cotton::Builtin::CF_removeglobal (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::removeGlobal(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_repr()
static Object* Cotton::Builtin::CF_repr (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__repr__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_setglobal()
static Object* Cotton::Builtin::CF_setglobal (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::NameIds::get(), Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::nds, ProfilerCAPTURE, Cotton::Runtime::setGlobal(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_sleep()
static Object* Cotton::Builtin::CF_sleep (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_smartrun()
static Object* Cotton::Builtin::CF_smartrun (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::checkGlobal(), Cotton::Runtime::error_manager, Cotton::Runtime::execute(), Cotton::NameIds::get(), Cotton::Runtime::getContext(), Cotton::Runtime::getGlobal(), getStringDataFast, Cotton::NameId::id, Cotton::Runtime::nds, Cotton::Runtime::newFrame(), Cotton::Parser::parse(), Cotton::Runtime::popFrame(), Cotton::Lexer::processFile(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::setGlobal(), Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_string()
static Object* Cotton::Builtin::CF_string (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::MagicMethods::mm__string__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), Cotton::Runtime::verifyHasMethod(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CF_system()
static Object* Cotton::Builtin::CF_system (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBuiltinFunctions().
CF_typeof()
static Object* Cotton::Builtin::CF_typeof (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::getTypeObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsValidObject().
Referenced by installBuiltinFunctions().
CharacterAddAdapter()
static Object* Cotton::Builtin::CharacterAddAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterEqAdapter()
static Object* Cotton::Builtin::CharacterEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by CharacterNeqAdapter(), and Cotton::Builtin::CharacterType::CharacterType().
CharacterGeqAdapter()
static Object* Cotton::Builtin::CharacterGeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterGtAdapter()
static Object* Cotton::Builtin::CharacterGtAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterLeqAdapter()
static Object* Cotton::Builtin::CharacterLeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterLtAdapter()
static Object* Cotton::Builtin::CharacterLtAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterNegativeAdapter()
static Object* Cotton::Builtin::CharacterNegativeAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterNeqAdapter()
static Object* Cotton::Builtin::CharacterNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References CharacterEqAdapter(), getBooleanValueFast, ProfilerCAPTURE, Cotton::Runtime::protected_false, and Cotton::Runtime::protected_true.
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterPositiveAdapter()
static Object* Cotton::Builtin::CharacterPositiveAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterPostdecAdapter()
static Object* Cotton::Builtin::CharacterPostdecAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterPostincAdapter()
static Object* Cotton::Builtin::CharacterPostincAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterPredecAdapter()
static Object* Cotton::Builtin::CharacterPredecAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterPreincAdapter()
static Object* Cotton::Builtin::CharacterPreincAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
CharacterSubAdapter()
static Object* Cotton::Builtin::CharacterSubAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::CharacterType::CharacterType().
charToString()
static std::string Cotton::Builtin::charToString (char c) [static]
References ProfilerCAPTURE.
Referenced by Cotton::Builtin::CharacterInstance::userRepr().
FunctionCallAdapter()
static Object* Cotton::Builtin::FunctionCallAdapter (Object * self, const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Scope::addVariable(), Cotton::Runtime::ErrorContext::area, Cotton::Scope::arguments, Cotton::Runtime::execute(), Cotton::Runtime::function_type, Cotton::Runtime::getContext(), icast, makeNothingInstanceObject(), Cotton::Runtime::newFrame(), Cotton::Runtime::popFrame(), ProfilerCAPTURE, Cotton::Runtime::scope, Cotton::Runtime::signalError(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::FunctionType::FunctionType().
FunctionEqAdapter()
static Object* Cotton::Builtin::FunctionEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::function_type, Cotton::Runtime::getContext(), icast, Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by FunctionNeqAdapter(), and Cotton::Builtin::FunctionType::FunctionType().
FunctionNeqAdapter()
static Object* Cotton::Builtin::FunctionNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References FunctionEqAdapter(), getBooleanValueFast, ProfilerCAPTURE, Cotton::Runtime::protected_false, and Cotton::Runtime::protected_true.
Referenced by Cotton::Builtin::FunctionType::FunctionType().
getArrayData() [1/2]
std::vector< Object * > & Cotton::Builtin::getArrayData (Object * obj, Runtime * rt)
References Cotton::Runtime::array_type, icast, Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
getArrayData() [2/2]
std::vector< Object * > & Cotton::Builtin::getArrayData (Object * obj, Runtime * rt, const TextArea & ta)
References Cotton::Runtime::array_type, icast, Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
getBooleanValue() [1/2]
bool & Cotton::Builtin::getBooleanValue (Object * obj, Runtime * rt)
References Cotton::Runtime::boolean_type, icast, Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by BooleanNeqAdapter(), Cotton::Runtime::execute(), and Cotton::Runtime::Runtime().
getBooleanValue() [2/2]
bool & Cotton::Builtin::getBooleanValue (Object * obj, Runtime * rt, const TextArea & ta)
References Cotton::Runtime::boolean_type, icast, Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
getCharacterValue() [1/2]
uint8_t & Cotton::Builtin::getCharacterValue (Object * obj, Runtime * rt)
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::character_type, Cotton::Runtime::getContext(), icast, Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
getCharacterValue() [2/2]
uint8_t & Cotton::Builtin::getCharacterValue (Object * obj, Runtime * rt, const TextArea & ta)
References Cotton::Runtime::character_type, icast, Cotton::Object::instance, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
getIntegerValue() [1/2]
int64_t & Cotton::Builtin::getIntegerValue (Object * obj, Runtime * rt)
References icast, Cotton::Object::instance, Cotton::Runtime::integer_type, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by CF_argg().
getIntegerValue() [2/2]
int64_t & Cotton::Builtin::getIntegerValue (Object * obj, Runtime * rt, const TextArea & ta)
References icast, Cotton::Object::instance, Cotton::Runtime::integer_type, ProfilerCAPTURE, and Cotton::Runtime::verifyIsInstanceObject().
getRealValue() [1/2]
double & Cotton::Builtin::getRealValue (Object * obj, Runtime * rt)
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), icast, Cotton::Object::instance, ProfilerCAPTURE, Cotton::Runtime::real_type, and Cotton::Runtime::verifyIsInstanceObject().
getRealValue() [2/2]
double & Cotton::Builtin::getRealValue (Object * obj, Runtime * rt, const TextArea & ta)
References icast, Cotton::Object::instance, ProfilerCAPTURE, Cotton::Runtime::real_type, and Cotton::Runtime::verifyIsInstanceObject().
getStringData() [1/2]
std::string & Cotton::Builtin::getStringData (Object * obj, Runtime * rt)
References icast, Cotton::Object::instance, ProfilerCAPTURE, Cotton::Runtime::string_type, and Cotton::Runtime::verifyIsInstanceObject().
getStringData() [2/2]
std::string & Cotton::Builtin::getStringData (Object * obj, Runtime * rt, const TextArea & ta)
References icast, Cotton::Object::instance, ProfilerCAPTURE, Cotton::Runtime::string_type, and Cotton::Runtime::verifyIsInstanceObject().
installArrayMethods()
void Cotton::Builtin::installArrayMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), arrayResizeMethod(), arraySizeMethod(), Cotton::NameIds::get(), Cotton::NameId::id, makeFunctionInstanceObject(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Runtime::Runtime().
installBooleanMethods()
void Cotton::Builtin::installBooleanMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), makeFunctionInstanceObject(), mm__bool__(), Cotton::MagicMethods::mm__bool__(), mm__char__(), Cotton::MagicMethods::mm__char__(), mm__int__(), Cotton::MagicMethods::mm__int__(), mm__read__(), Cotton::MagicMethods::mm__read__(), mm__real__(), Cotton::MagicMethods::mm__real__(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), mm__string__(), Cotton::MagicMethods::mm__string__(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::Runtime().
installBuiltinFunctions()
void Cotton::Builtin::installBuiltinFunctions (Runtime * rt)
References Cotton::Scope::addVariable(), CF_argc(), CF_argg(), CF_argv(), CF_assert(), CF_bool(), CF_char(), CF_checkglobal(), CF_copy(), CF_cotton(), CF_dumbrun(), CF_error(), CF_exit(), CF_fork(), CF_getglobal(), CF_hasfield(), CF_hasmethod(), CF_int(), CF_isinsobj(), CF_istypeobj(), CF_loadlibrary(), CF_make(), CF_print(), CF_printf(), CF_println(), CF_printraw(), CF_read(), CF_readln(), CF_readraw(), CF_real(), CF_removeglobal(), CF_repr(), CF_setglobal(), CF_sleep(), CF_smartrun(), CF_string(), CF_system(), CF_typeof(), Cotton::NameIds::get(), Cotton::NameId::id, makeFunctionInstanceObject(), Cotton::Runtime::nds, ProfilerCAPTURE, and Cotton::Runtime::scope.
Referenced by Cotton::Runtime::Runtime().
installCharacterMethods()
void Cotton::Builtin::installCharacterMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), makeFunctionInstanceObject(), mm__bool__(), Cotton::MagicMethods::mm__bool__(), mm__char__(), Cotton::MagicMethods::mm__char__(), mm__int__(), Cotton::MagicMethods::mm__int__(), mm__read__(), Cotton::MagicMethods::mm__read__(), mm__real__(), Cotton::MagicMethods::mm__real__(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), mm__string__(), Cotton::MagicMethods::mm__string__(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::Runtime().
installFunctionMethods()
void Cotton::Builtin::installFunctionMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), makeFunctionInstanceObject(), mm__repr__(), and Cotton::MagicMethods::mm__repr__().
Referenced by Cotton::Runtime::Runtime().
installIntegerMethods()
void Cotton::Builtin::installIntegerMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), makeFunctionInstanceObject(), mm__bool__(), Cotton::MagicMethods::mm__bool__(), mm__char__(), Cotton::MagicMethods::mm__char__(), mm__int__(), Cotton::MagicMethods::mm__int__(), mm__read__(), Cotton::MagicMethods::mm__read__(), mm__real__(), Cotton::MagicMethods::mm__real__(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), mm__string__(), Cotton::MagicMethods::mm__string__(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::Runtime().
installNothingMethods()
void Cotton::Builtin::installNothingMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), makeFunctionInstanceObject(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::Runtime().
installRealMethods()
void Cotton::Builtin::installRealMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), makeFunctionInstanceObject(), mm__bool__(), Cotton::MagicMethods::mm__bool__(), mm__char__(), Cotton::MagicMethods::mm__char__(), mm__int__(), Cotton::MagicMethods::mm__int__(), mm__read__(), Cotton::MagicMethods::mm__read__(), mm__real__(), Cotton::MagicMethods::mm__real__(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), mm__string__(), Cotton::MagicMethods::mm__string__(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::Runtime().
installStringMethods()
void Cotton::Builtin::installStringMethods (Type * type, Runtime * rt)
References Cotton::Type::addMethod(), Cotton::NameIds::get(), Cotton::NameId::id, makeFunctionInstanceObject(), mm__bool__(), Cotton::MagicMethods::mm__bool__(), mm__int__(), Cotton::MagicMethods::mm__int__(), mm__read__(), Cotton::MagicMethods::mm__read__(), mm__real__(), Cotton::MagicMethods::mm__real__(), mm__repr__(), Cotton::MagicMethods::mm__repr__(), mm__string__(), Cotton::MagicMethods::mm__string__(), Cotton::Runtime::nds, ProfilerCAPTURE, stringSetMethod(), and stringSizeMethod().
Referenced by Cotton::Runtime::Runtime().
IntegerAddAdapter()
static Object* Cotton::Builtin::IntegerAddAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerBitandAdapter()
static Object* Cotton::Builtin::IntegerBitandAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerBitorAdapter()
static Object* Cotton::Builtin::IntegerBitorAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerBitxorAdapter()
static Object* Cotton::Builtin::IntegerBitxorAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerDivAdapter()
static Object* Cotton::Builtin::IntegerDivAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerEqAdapter()
static Object* Cotton::Builtin::IntegerEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by IntegerNeqAdapter(), and Cotton::Builtin::IntegerType::IntegerType().
IntegerGeqAdapter()
static Object* Cotton::Builtin::IntegerGeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerGtAdapter()
static Object* Cotton::Builtin::IntegerGtAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerInverseAdapter()
static Object* Cotton::Builtin::IntegerInverseAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerLeqAdapter()
static Object* Cotton::Builtin::IntegerLeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerLshiftAdapter()
static Object* Cotton::Builtin::IntegerLshiftAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerLtAdapter()
static Object* Cotton::Builtin::IntegerLtAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerMultAdapter()
static Object* Cotton::Builtin::IntegerMultAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerNegativeAdapter()
static Object* Cotton::Builtin::IntegerNegativeAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerNeqAdapter()
static Object* Cotton::Builtin::IntegerNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References getBooleanValueFast, IntegerEqAdapter(), ProfilerCAPTURE, Cotton::Runtime::protected_false, and Cotton::Runtime::protected_true.
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerPositiveAdapter()
static Object* Cotton::Builtin::IntegerPositiveAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerPostdecAdapter()
static Object* Cotton::Builtin::IntegerPostdecAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerPostincAdapter()
static Object* Cotton::Builtin::IntegerPostincAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerPredecAdapter()
static Object* Cotton::Builtin::IntegerPredecAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerPreincAdapter()
static Object* Cotton::Builtin::IntegerPreincAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerRemAdapter()
static Object* Cotton::Builtin::IntegerRemAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerRshiftAdapter()
static Object* Cotton::Builtin::IntegerRshiftAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
IntegerSubAdapter()
static Object* Cotton::Builtin::IntegerSubAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::IntegerType::IntegerType().
makeArrayInstanceObject()
Object * Cotton::Builtin::makeArrayInstanceObject (const std::vector< Object * > & data, Runtime * rt)
References Cotton::Runtime::array_type, getArrayDataFast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), and ProfilerCAPTURE.
Referenced by CF_argv().
makeBooleanInstanceObject()
Object * Cotton::Builtin::makeBooleanInstanceObject (bool value, Runtime * rt)
References Cotton::Runtime::boolean_type, icast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::execute(), and mm__bool__().
makeCharacterInstanceObject()
Object * Cotton::Builtin::makeCharacterInstanceObject (uint8_t value, Runtime * rt)
References Cotton::Runtime::character_type, icast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), and ProfilerCAPTURE.
Referenced by CF_readraw(), CharacterAddAdapter(), CharacterSubAdapter(), Cotton::Runtime::execute(), mm__char__(), mm__read__(), and StringIndexAdapter().
makeFunctionInstanceObject()
Object * Cotton::Builtin::makeFunctionInstanceObject (bool is_internal, InternalFunction internal_ptr, FuncDefNode * cotton_ptr, Runtime * rt)
References Cotton::Runtime::function_type, icast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), and ProfilerCAPTURE.
Referenced by Cotton::Runtime::execute(), installArrayMethods(), installBooleanMethods(), installBuiltinFunctions(), installCharacterMethods(), installFunctionMethods(), installIntegerMethods(), installNothingMethods(), installRealMethods(), installStringMethods(), and library_load_point().
makeIntegerInstanceObject()
Object * Cotton::Builtin::makeIntegerInstanceObject (int64_t value, Runtime * rt)
References icast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::integer_type, Cotton::Runtime::make(), and ProfilerCAPTURE.
Referenced by arraySizeMethod(), CF_argc(), CF_fork(), CF_system(), Cotton::Runtime::execute(), IntegerAddAdapter(), IntegerBitandAdapter(), IntegerBitorAdapter(), IntegerBitxorAdapter(), IntegerDivAdapter(), IntegerLshiftAdapter(), IntegerMultAdapter(), IntegerRemAdapter(), IntegerRshiftAdapter(), IntegerSubAdapter(), mm__int__(), mm__read__(), and stringSizeMethod().
makeNothingInstanceObject()
Object * Cotton::Builtin::makeNothingInstanceObject (Runtime * rt)
References Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), Cotton::Runtime::nothing_type, and ProfilerCAPTURE.
Referenced by arrayResizeMethod(), Cotton::Builtin::RecordType::create(), Cotton::Runtime::execute(), and FunctionCallAdapter().
makeRealInstanceObject()
Object * Cotton::Builtin::makeRealInstanceObject (double value, Runtime * rt)
References icast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), ProfilerCAPTURE, and Cotton::Runtime::real_type.
Referenced by Cotton::Runtime::execute(), mm__read__(), mm__real__(), RealAddAdapter(), RealDivAdapter(), RealMultAdapter(), and RealSubAdapter().
makeRecordInstanceObject()
Object* Cotton::Builtin::makeRecordInstanceObject (Runtime * rt)
References Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), Cotton::Runtime::nothing_type, and ProfilerCAPTURE.
makeRecordType()
RecordType * Cotton::Builtin::makeRecordType (int64_t nameid, Runtime * rt)
References ProfilerCAPTURE.
Referenced by library_load_point().
makeStringInstanceObject()
Object * Cotton::Builtin::makeStringInstanceObject (const std::string & value, Runtime * rt)
References getStringDataFast, Cotton::Runtime::INSTANCE_OBJECT, Cotton::Runtime::make(), ProfilerCAPTURE, and Cotton::Runtime::string_type.
Referenced by CF_readln(), Cotton::Runtime::execute(), library_load_point(), mm__read__(), mm__repr__(), and mm__string__().
mm__bool__() [1/5]
static Object* Cotton::Builtin::mm__bool__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBooleanMethods(), installCharacterMethods(), installIntegerMethods(), installRealMethods(), and installStringMethods().
mm__bool__() [2/5]
static Object* Cotton::Builtin::mm__bool__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), makeBooleanInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__bool__() [3/5]
static Object* Cotton::Builtin::mm__bool__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__bool__() [4/5]
static Object* Cotton::Builtin::mm__bool__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__bool__() [5/5]
static Object* Cotton::Builtin::mm__bool__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::getContext(), getStringDataFast, ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__char__() [1/4]
static Object* Cotton::Builtin::mm__char__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBooleanMethods(), installCharacterMethods(), installIntegerMethods(), and installRealMethods().
mm__char__() [2/4]
static Object* Cotton::Builtin::mm__char__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__char__() [3/4]
static Object* Cotton::Builtin::mm__char__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__char__() [4/4]
static Object* Cotton::Builtin::mm__char__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__int__() [1/5]
static Object* Cotton::Builtin::mm__int__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBooleanMethods(), installCharacterMethods(), installIntegerMethods(), installRealMethods(), and installStringMethods().
mm__int__() [2/5]
static Object* Cotton::Builtin::mm__int__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__int__() [3/5]
static Object* Cotton::Builtin::mm__int__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__int__() [4/5]
static Object* Cotton::Builtin::mm__int__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__int__() [5/5]
static Object* Cotton::Builtin::mm__int__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__read__() [1/5]
static Object* Cotton::Builtin::mm__read__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::ErrorContext::area, Cotton::Runtime::boolean_type, Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::signalError(), Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
Referenced by installBooleanMethods(), installCharacterMethods(), installIntegerMethods(), installRealMethods(), and installStringMethods().
mm__read__() [2/5]
static Object* Cotton::Builtin::mm__read__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, Cotton::Runtime::getContext(), makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__read__() [3/5]
static Object* Cotton::Builtin::mm__read__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::integer_type, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__read__() [4/5]
static Object* Cotton::Builtin::mm__read__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__read__() [5/5]
static Object* Cotton::Builtin::mm__read__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__real__() [1/5]
static Object* Cotton::Builtin::mm__real__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installBooleanMethods(), installCharacterMethods(), installIntegerMethods(), installRealMethods(), and installStringMethods().
mm__real__() [2/5]
static Object* Cotton::Builtin::mm__real__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__real__() [3/5]
static Object* Cotton::Builtin::mm__real__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__real__() [4/5]
static Object* Cotton::Builtin::mm__real__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__real__() [5/5]
static Object* Cotton::Builtin::mm__real__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__repr__() [1/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::array_type, getArrayDataFast, Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), Cotton::MagicMethods::mm__repr__(), ProfilerCAPTURE, Cotton::Runtime::runMethod(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), Cotton::Runtime::verifyIsInstanceObject(), and Cotton::Runtime::verifyIsOfType().
Referenced by installArrayMethods(), installBooleanMethods(), installCharacterMethods(), installFunctionMethods(), installIntegerMethods(), installNothingMethods(), installRealMethods(), and installStringMethods().
mm__repr__() [2/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__repr__() [3/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__repr__() [4/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::function_type, Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__repr__() [5/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__repr__() [6/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), Cotton::Runtime::nothing_type, ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__repr__() [7/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__repr__() [8/8]
static Object* Cotton::Builtin::mm__repr__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__string__() [1/5]
static Object* Cotton::Builtin::mm__string__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::boolean_type, getBooleanValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
Referenced by installBooleanMethods(), installCharacterMethods(), installIntegerMethods(), installRealMethods(), and installStringMethods().
mm__string__() [2/5]
static Object* Cotton::Builtin::mm__string__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), Cotton::Runtime::isTypeObject(), makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsOfType().
mm__string__() [3/5]
static Object* Cotton::Builtin::mm__string__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, Cotton::Runtime::integer_type, makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__string__() [4/5]
static Object* Cotton::Builtin::mm__string__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
mm__string__() [5/5]
static Object* Cotton::Builtin::mm__string__ (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, makeStringInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
NothingEqAdapter()
static Object* Cotton::Builtin::NothingEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), Cotton::Runtime::isOfType(), Cotton::Runtime::nothing_type, ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by NothingNeqAdapter(), and Cotton::Builtin::NothingType::NothingType().
NothingNeqAdapter()
static Object* Cotton::Builtin::NothingNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References getBooleanValueFast, NothingEqAdapter(), ProfilerCAPTURE, Cotton::Runtime::protected_false, and Cotton::Runtime::protected_true.
Referenced by Cotton::Builtin::NothingType::NothingType().
RealAddAdapter()
static Object* Cotton::Builtin::RealAddAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealDivAdapter()
static Object* Cotton::Builtin::RealDivAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealEqAdapter()
static Object* Cotton::Builtin::RealEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by RealNeqAdapter(), and Cotton::Builtin::RealType::RealType().
RealGeqAdapter()
static Object* Cotton::Builtin::RealGeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealGtAdapter()
static Object* Cotton::Builtin::RealGtAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealLeqAdapter()
static Object* Cotton::Builtin::RealLeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealLtAdapter()
static Object* Cotton::Builtin::RealLtAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealMultAdapter()
static Object* Cotton::Builtin::RealMultAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealNegativeAdapter()
static Object* Cotton::Builtin::RealNegativeAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealNeqAdapter()
static Object* Cotton::Builtin::RealNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References getBooleanValueFast, ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, and RealEqAdapter().
Referenced by Cotton::Builtin::RealType::RealType().
RealPositiveAdapter()
static Object* Cotton::Builtin::RealPositiveAdapter (Object * self, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
RealSubAdapter()
static Object* Cotton::Builtin::RealSubAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getRealValueFast, makeRealInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::real_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::RealType::RealType().
StringAddAdapter()
static Object* Cotton::Builtin::StringAddAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::copy(), Cotton::Runtime::getContext(), getStringDataFast, ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::StringType::StringType().
StringEqAdapter()
static Object* Cotton::Builtin::StringEqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, Cotton::Runtime::integer_type, Cotton::Runtime::isInstanceObject(), Cotton::Runtime::isOfType(), Cotton::Runtime::isTypeObject(), ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, Cotton::Runtime::protectedBoolean(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyIsOfType(), and Cotton::Runtime::verifyIsValidObject().
Referenced by StringNeqAdapter(), and Cotton::Builtin::StringType::StringType().
StringIndexAdapter()
static Object* Cotton::Builtin::StringIndexAdapter (Object * self, const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getIntegerValueFast, getStringDataFast, Cotton::Runtime::integer_type, makeCharacterInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountFunc(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by Cotton::Builtin::StringType::StringType().
StringNeqAdapter()
static Object* Cotton::Builtin::StringNeqAdapter (Object * self, Object * arg, Runtime * rt, bool execution_result_matters) [static]
References getBooleanValueFast, ProfilerCAPTURE, Cotton::Runtime::protected_false, Cotton::Runtime::protected_true, and StringEqAdapter().
Referenced by Cotton::Builtin::StringType::StringType().
stringSetMethod()
static Object* Cotton::Builtin::stringSetMethod (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::character_type, getCharacterValueFast, Cotton::Runtime::getContext(), getIntegerValueFast, getStringDataFast, Cotton::Runtime::integer_type, ProfilerCAPTURE, Cotton::Runtime::protected_nothing, Cotton::Runtime::signalError(), Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installStringMethods().
stringSizeMethod()
static Object* Cotton::Builtin::stringSizeMethod (const std::vector< Object * > & args, Runtime * rt, bool execution_result_matters) [static]
References Cotton::Runtime::getContext(), getStringDataFast, makeIntegerInstanceObject(), ProfilerCAPTURE, Cotton::Runtime::string_type, Cotton::Runtime::ErrorContext::sub_areas, Cotton::Runtime::verifyExactArgsAmountMethod(), and Cotton::Runtime::verifyIsInstanceObject().
Referenced by installStringMethods().