Cotton::MagicMethods Namespace Reference
Functions
int64_t mm__make__ (Runtime *rt)
int64_t mm__copy__ (Runtime *rt)
int64_t mm__bool__ (Runtime *rt)
int64_t mm__char__ (Runtime *rt)
int64_t mm__int__ (Runtime *rt)
int64_t mm__real__ (Runtime *rt)
int64_t mm__string__ (Runtime *rt)
int64_t mm__repr__ (Runtime *rt)
int64_t mm__read__ (Runtime *rt)
Function Documentation
mm__bool__()
int64_t Cotton::MagicMethods::mm__bool__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_bool(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installRealMethods(), and Cotton::Builtin::installStringMethods().
mm__char__()
int64_t Cotton::MagicMethods::mm__char__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_char(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installIntegerMethods(), and Cotton::Builtin::installRealMethods().
mm__copy__()
int64_t Cotton::MagicMethods::mm__copy__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_copy().
mm__int__()
int64_t Cotton::MagicMethods::mm__int__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_int(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installRealMethods(), and Cotton::Builtin::installStringMethods().
mm__make__()
int64_t Cotton::MagicMethods::mm__make__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_make().
mm__read__()
int64_t Cotton::MagicMethods::mm__read__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_read(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installRealMethods(), and Cotton::Builtin::installStringMethods().
mm__real__()
int64_t Cotton::MagicMethods::mm__real__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_real(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installRealMethods(), and Cotton::Builtin::installStringMethods().
mm__repr__()
int64_t Cotton::MagicMethods::mm__repr__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_printraw(), Cotton::Builtin::CF_repr(), Cotton::Builtin::installArrayMethods(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installFunctionMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installNothingMethods(), Cotton::Builtin::installRealMethods(), Cotton::Builtin::installStringMethods(), and Cotton::Builtin::mm__repr__().
mm__string__()
int64_t Cotton::MagicMethods::mm__string__ (Runtime * rt)
References Cotton::NameIds::get(), Cotton::NameId::id, Cotton::Runtime::nds, and ProfilerCAPTURE.
Referenced by Cotton::Builtin::CF_string(), Cotton::Builtin::installBooleanMethods(), Cotton::Builtin::installCharacterMethods(), Cotton::Builtin::installIntegerMethods(), Cotton::Builtin::installRealMethods(), and Cotton::Builtin::installStringMethods().